elastic/fleet-server

.gitignore
build/package/Dockerfile
build/package/docker-compose.yml
build/rpm/nfpm.yaml
systemd/fleet.service

* Put back the build/ directory that was lost during the repo move.
* Adjusted the Dockerfile to fix the image for the config file and changes project structure (main.go) in ./
* Updated RPM spec and systemd file to include fleet-server.yml

Fix docker image build

---

.ci/jobs/defaults.yml
.ci/jobs/fleet-server.yml
.ci/jobs/folders.yml

Initial requirement to create the MBP in the Jenkins instance.
- Once the infra enable the JJB creationg, I'll proceed to merge this PR and create another PR to provide the Jenkinsfile

[jjbb][CI] Add jobs definition

---

.ci/jobs/fleet-server.yml

GitHub APP is not enabled for this project

[jjbb] use usertoken

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/flaky-test.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/comment.yml
.github/labels.yml
.github/paths-labeller.yml
.github/relabel.yml
.github/stale.yml

Add initial automation rules based on the rules from the beats

---

README.md

Cosmetic change with the build status in the README.md
Easy to visualise what's going on in the CI

[CI] Add CI build status

---

fleet-server.yml

Fixes issue where the configuration file didn't nest the `elasticsearch` under `output`.
So the default configuration will use the environment variables defined in the configuration.

Fix default configuration file

---

cmd/fleet/handleCheckin.go
cmd/fleet/main.go
cmd/fleet/server.go
cmd/fleet/server_test.go
internal/pkg/es/client.go
internal/pkg/profile/profile.go
internal/pkg/runner/runner.go

* Refactored restart cancellation and some repetitive code.
* Moved the cancellables from the server struct scope into the "Runnable" function scope. I think this way the cancellation handling is cleaner and doesn't require locking, synchronization.
* Trimmed the server Reload function.
@blakerouse let me know what you think

Refactor restart

---

internal/pkg/coordinator/monitor.go
internal/pkg/sleep/sleep.go
internal/pkg/testing/retry.go

Consolidate sleep.WithContext.
Same pattern is used in couple of places.

Consolidate sleep.WithContext

---

.ci/Jenkinsfile
Makefile

Enable JUnit reporting in the CI.
Honour the GitHub comments that report any test failures.

[CI] Enable JUnit

---

cmd/fleet/auth.go
cmd/fleet/handleAck.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/schema.go
cmd/fleet/server_integration_test.go
cmd/fleet/server_test.go
internal/pkg/cache/cache.go
internal/pkg/dl/actions.go
internal/pkg/dl/constants.go

Handles the resulting ACK of `UNENROLL` action.
This also moves the cache to not be a global, not a fan of globals.
So the Agent is marked correctly on successful ack of `UNENROLL`.

Handle ack of UNENROLL.

---

cmd/fleet/handleCheckin.go
cmd/fleet/schema.go

Add missing input_id for the action

Add missing input_id for the action

---

README.md

As discussed with @aleksmaus  add documentation on how to run Fleet Server with Kibana as soon https://github.com/elastic/kibana/pull/86179 is merged.

[Fleet] Document how to use with Kibana

---

dev-tools/cherrypick_pr

Adds the `dev-tools/cherrypick_pr` helper script to help cherrypick changes from `master` to `7.x` branches.
`7.x` branch is now created for release manager building, so we need to start backporting any changes to that branch.

Add cherrypick_pr dev-tools helper.

---

main.go

Set the version of the `7.x` branch to `7.12.0`.
So building of packages for the `7.x` branch is correct.

Set version to 7.12.0.

---

.ci/Jenkinsfile

Minor changes to speed up the checkout
Faster builds

[CI] Skip implicit checkout in the stages

---

README.md

The instructions on how to run Fleet Server with Kibana should be most simpler now.

[Fleet] Update how to run with Kibana instructions

---

main.go

Bump `7.x` version to `7.13`
For the release of `7.12`.

Bump version to 7.13.

---

cmd/fleet/schema.go

Remove unnecessary write privileges from output api key.  Same as currently in kibana: https://github.com/elastic/kibana/commit/a936fe67a6d906f67a99a88fe772876dc461c530
Fleet should limit the privileges afforded to untrusted endpoints.  Note: these privileges are still too broad; attacker could leverage to DOS with data stream creation or mapping explosion.
- [ x] I have added an entry in `CHANGELOG.next.asciidoc` or …

Align output key permissions with 7.12 Kibana

---

cmd/fleet/schema.go

Backport master commit for privs.

[Backport 7.x] Align permission keys with Kibana 7.12

---

internal/pkg/monitor/global_checkpoint.go

Fixes the indices monitoring, that got broken due to replacing the original
.fleet-actions and .fleet-policies indices with aliases.
This change uses the first index global checkpoint value received from
stats and returns the error if there are more than one index for
alias for any reason.
- Closes https://github.com/elastic/fleet-server/issues/115
before 
after
This unblocks the devs dependent on this feature ASAP. 
Will follow up with an issue that possibly reports degraded status to the agent instead and unit tests coverage.

Fix global checkpoint based monitoring

---

Makefile

- Enables ASLR build on 64-bit machines.
- Remove 32bit builds.  Fleet Server should not execute on 32bit machine for security reasons.  In particular, ASLR is not effective on 32bit machines.
[ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) is an important security mitigation.
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
Run make release.
Run tool on …

Support buildmode=pie on 64 bit platforms.

---

cmd/fleet/auth.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/router.go
internal/pkg/cache/cache.go
internal/pkg/dl/artifact.go
internal/pkg/dl/constants.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
internal/pkg/throttle/throttle.go
internal/pkg/throttle/throttle_test.go
model/schema.json

backport 130 -> artifact support

Backport 130 7.x

---

cmd/fleet/main.go
cmd/fleet/server_integration_test.go
cmd/fleet/server_test.go
internal/pkg/cache/cache.go
internal/pkg/config/cache.go
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/throttle/throttle_test.go

(cherry picked from commit 4c97d5396750ade202c939e6ceb4aed1aa1152de)
backport from master to 7.x

Add cache configuration option.

---

internal/pkg/dl/constants.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Initial .fleet-artifacts mapping were in camelCase.  Switched to snake_case to conform to other mappings.
Field names are part of the contract.
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

Move from camelCase to snake_case to reflect change in Kibana.

---

cmd/fleet/schema.go

(cherry picked from commit 7c4449bae782dee013ad21ff63599d088c8147bb)
Backport event payload type.
-

Update Event payload type. (#128)

---

main.go

Bump to 7.12.1

---

cmd/fleet/handleAck.go
cmd/fleet/schema.go
internal/pkg/dl/constants.go

Handles the upgrade ACK so that the `.fleet-agents` document is updated correctly.
Without it the Elastic Agent is stuck in upgrading forever in Kibana.

Fix the handling of the upgrade ack.

---

internal/pkg/config/logging.go
internal/pkg/logger/logger.go

Optionally makes stderr easier to read when debugging.  Off by default.
JSON output hard to read.

Add pretty print logger output under stderr

---

internal/pkg/logger/logger.go

Output logs ECS compatible way.
To align with other products.
- Closes https://github.com/elastic/fleet-server/issues/206

Support basic ECS logging fields

---

NOTICE.txt
cmd/fleet/handleAck.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/handleStatus.go
cmd/fleet/metrics.go
cmd/fleet/server.go
go.mod
go.sum
internal/pkg/policy/monitor.go

Adds additional stats to each HTTP route for visibility.
Provides runtime usage data at a per route granular level.
Make sure that the metrics server is enabled in your yaml settings file
:
- Relates https://github.com/elastic/beats/issues/24415

Add route metrics.

---

README.md

Backport readme changes.
People get grumpy when the docs are out of date.

Bring 7.x readme up to date with master.

---

example/fleet-server-100.yml

Example configuration for minimal footprint.
Free tier must run Fleet Server in as small of a footprint as possible.
Use config file as a template and start Fleet Server.

Example configuration for minimal RAM.

---

README.md

I currently writing this docs so everyone wanted to get running with fleet-server has a single place to read up on it. Later on, this will be converted to proper docs.

Add docs about fleet-server compatibility and enrollment

---

main.go

Bump to 7.14.0
mergify rules were done in https://github.com/elastic/fleet-server/pull/261
-

Bump to 7.14.0

---

.ci/bump-stack-version.sh
.ci/jobs/fleet-server.yml
.mergify.yml

Remove branches that were generated with the given pattern
Avoid builds for the branches created with some automation in mergify.
Unique branch id with the base branch in the name.

[mergify]: delete branch related to automation after it gets merged and commit messages

---

internal/pkg/policy/monitor.go
internal/pkg/policy/revision.go

Removes the checks on the policy ID being a UUID.
It is possible that a policy ID is not a UUID, and there is no requirement that it needs to be.
- Closes #285

Remove the UUID checks.

---

main.go

7.12.1 was released so we bump the branch to 7.12.2
-

Bump to 7.12.2 from 7.12.1

---

cmd/fleet/main.go
cmd/fleet/metrics.go

When running under Elastic Agent the Fleet Server will report the failure to Elastic Agent instead of crashing.
So that the process is not in a constant restart loop when an error occurs.
- Closes #235

Report failure running under Elastic Agent

---

cmd/fleet/error.go
cmd/fleet/handleAck.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/metrics.go
cmd/fleet/server_integration_test.go

Any time the API returns an error to an HTTP request it should be JSON so it can be decoded by the Elastic Agent.
So proper and easy to understand error messages are reported by the Elastic Agent.
- Closes #323

Add error response to be JSON

---

.github/workflows/project-assigner.yml

Testing auto assign board

---

cmd/fleet/main.go
fleet-server.yml

Fixes issue where configuration reloading did not reload all the areas that it needed to. This was because the code path used the original configuration it was started with and not the configuration passed in from the reload.
So configuration reloading works correctly.
- Closes #172

Fix issue with config reloading

---

Makefile
cmd/fleet/main.go
internal/pkg/logger/logger.go
main.go

Log commit id and version at boot time.

Backport commit logging at boot time

---

main.go

Bump the `defaultVersion` to 7.13.1 so builds will use that as the version.
For release manager.

Bump to 7.13.1

---

main.go

Part of 7.13.1 release process.
To be merged on release day

Bump version to 7.13.2

---

cmd/fleet/handleEnroll.go

Slight improvement to enrollment logging
Need better visibility.

Better enroll logging

---

main.go

Part of 7.13.2 release process.
To be merged on release day

Bump version to 7.13.3

---

README.md

It resolves conflicts added in 7c29697c2ee004a13e12c67887b3092f60dd440f
Keep branch healthy
- Caused by #397

fix: resolve missed merge-conflicts

---

main.go

Bumps 7.x to 7.15.
Release of 7.14.

Bump 7.x to 7.15.

---

cmd/fleet/server.go

Enables http2 on Fleet Server's HTTP interface.  The protocol is not supported implicitly when creating a server with the more sophisticated API calls.
Agent expects HTTP2 now.  System is broken.

Enable http2 in Fleet Server.

---

.mergify.yml

Updates the mergify configuration so that tags for 7.15 go to 7.x branch and tags for 7.14 go to 7.14 branch.
Release of 7.14.

Update mergify for 7.15

---

cmd/fleet/server.go

Cherry-pick of PR #511 to 7.14 branch. Original message: 
Enables http2 on Fleet Server's HTTP interface.  The protocol is not supported implicitly when creating a server with the more sophisticated API calls.
Agent expects HTTP2 now.  System is broken.

Cherry-pick #511 to 7.14: Enable http2 in Fleet Server.

---

main.go

Part of 7.13.3 release process.
To be merged on release day

Bump version to 7.13.4

---

main.go

Bump to 7.13.5, for release of 7.13.4.
Release of 7.13.4.

Bump to 7.13.5.

---

main.go

Revert "Bump to 7.13.5. (#530)"

---

internal/pkg/policy/monitor.go
internal/pkg/policy/sub.go
internal/pkg/policy/sub_test.go

Reworks the policy rollout to be fairer and more controlled.  Avoids bursts when a bunch of agents come online at once.
The server becomes overwhelmed if too many agents checkin at the same time after a policy change.

refactor rollout to be more deterministic

---

main.go

Bump version to 7.13.5 for release of 7.13.4.
Release of 7.13.4.

Bump 7.13.5

---

main.go

Part of 7.14.0 release. To be merged on release day

Bump version to 7.14.1

---

.ci/jobs/fleet-server.yml

It tells the CI to build those branches with following names:
- master
- 7.x
- 7.10+
- PRs
- releases (v.x.y.z)
To avoid building branches that are already PRs

fix(ci): narrow down what branches to build

---

cmd/fleet/handleCheckin.go
cmd/fleet/main.go
internal/pkg/coordinator/monitor.go

More logging for config change / policy change diagnostics.
Difficult to see behavior at 'info' level, and 'debug' level nearly impossible to enable at bootstrap given the way the current system works.

Add additional diagnostic logging to trace policy assignment issues.

---

cmd/fleet/handleAck.go
cmd/fleet/handleCheckin.go

Additional logging to track policy change.
Increased visibility into policy issues.

Additional logs to track policy change.

---

main.go

Bumps version to 7.16.0 for 7.x.
Release of 7.15.0.

Bump to 7.16.

---

.mergify.yml

Updates the `.mergify.yml` file to update the labels for backporting to 7.x for 7.16 and 7.15 for 7.15.
Release of 7.15.0.

Update mergify for 7.15 release.

---

main.go

This must be merged AFTER the 7.14.1 release.

Bump version to 7.14.2

---

main.go

Bump to 7.14.3

---

main.go

This needs to be merged after 7.15.0 is out.

Update release version to 7.15.1

---

main.go

Part of 7.15.1 release - to be merged on release day.

Bump version to 7.15.2

---

cmd/fleet/auth.go
cmd/fleet/error.go
cmd/fleet/handleAck.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/server.go
cmd/fleet/userAgent.go
cmd/fleet/userAgent_test.go
internal/pkg/action/dispatcher.go
internal/pkg/apikey/get.go
internal/pkg/config/input.go
internal/pkg/coordinator/monitor.go
internal/pkg/coordinator/v0.go
internal/pkg/es/client.go
internal/pkg/logger/ecs.go
internal/pkg/logger/http.go
internal/pkg/policy/monitor.go

This PR fixes several issues:
- Another pass at normalizing logging using field names that ElasticSearch will index.
- Uses the proper TLS structure for reading the configuration; thus enabling optional client validation.
- Handles case where enrollment response fails to write, removing orphaned records.
- Enables HTTP logging at the INFO level, adding addition logging if DEBUG enabled.
Refines the logging with constants.  Works the edge cases.

Normalize logging

---

main.go

To be merged on 7.15.2 release day.

Bump version to 7.15.3

---

cmd/fleet/handleAck.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/router.go
internal/pkg/bulk/helpers.go
internal/pkg/bulk/opRead.go
internal/pkg/coordinator/monitor.go
internal/pkg/monitor/monitor.go
internal/pkg/policy/monitor.go
internal/pkg/ver/check.go

This was coming out of the debugging session around fleet-server where some of the log messages were not too clear to me on what these mean.

Improve some of the log message

---

cmd/fleet/handleAck.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/router.go
internal/pkg/bulk/helpers.go
internal/pkg/bulk/opRead.go
internal/pkg/coordinator/monitor.go
internal/pkg/monitor/monitor.go
internal/pkg/policy/monitor.go
internal/pkg/ver/check.go

This was coming out of the debugging session around fleet-server where some of the log messages were not too clear to me on what these mean.

[7.16](backport #844) Improve some of the log message

---

cmd/fleet/handleAck.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/router.go
internal/pkg/bulk/helpers.go
internal/pkg/bulk/opRead.go
internal/pkg/coordinator/monitor.go
internal/pkg/monitor/monitor.go
internal/pkg/policy/monitor.go
internal/pkg/ver/check.go

This was coming out of the debugging session around fleet-server where some of the log messages were not too clear to me on what these mean.

[8.0](backport #844) Improve some of the log message

---

Makefile
cmd/fleet/handleAck.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleChecking_test.go
internal/pkg/cache/cache.go
internal/pkg/dl/constants.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Adds the API keys cleanup/invalidation.
1. If the API key needs to be updated, the old API keys are appended to the .fleet-agents ```default_api_key_history``` property.
2. When the policy ack is received the keys from the history are invalidated and the agent document ```default_api_key_history``` is reset
1. Enroll the agent, check the ```default_api_key``` and ```default_api_key_id```
2. Update the policy, by adding new integration. The permissions change will cause the API key to be regenerated and the old keys to be appended to the history. Should be able to observer the ```default_api_key_history``` updated with the previous key before the policy change ack is recieved:
3. When the policy ack is received, should be able to see in the fleet server log, the ```"Invalidate old API …
```

API keys cleanup

---

main.go

Bump version to 7.16.1

---

main.go

Bump version to 7.16.2

---

.mergify.yml

Add backport rule for 7.17 branch

---

main.go

Part of 7.16.2 release. To be merged before final release.

Version bump to 7.16.3

---

NOTICE.txt

Looks like the 8.0 branch is in failed state due to notice update. This fixes it.
Ran ```make check```, updated NOTICE.txt

 Fix 8.0 branch NOTICE.txt

---

main.go

Bump version to 7.16.4

---

main.go

To be merged on 7.17.0 release day.

[Release] Bump version to 7.17.1

---

.ci/jobs/fleet-server.yml
.mergify.yml
README.md
dev-tools/cherrypick_pr

Use `main` references
- Required to rename the default branch before merging.
- Required to apply the JJB engine changes in the infra side.

update main references

---

main.go

To be merged on 7.17.1 release day.

Bump version to 7.17.2

---

.ci/Jenkinsfile
Makefile

This code refactor the `make check` task, it split the task into two different concerns:
-  One is `make check-ci` which is run as part of the Jenkins files, this task deals with code generation, headers check, notice generation and make sure all the changes are checked in the VCS.
- The other is `make check` that run all the checks above and also golangci-lint. The pull request linter is doing using a github action to receive all the inline comments.
- Requires #1165
- Relates #1161

Refactor make check

---

main.go

To be merged on 8.1.0 release day

Bump version to 8.1.1

---

.ci/jobs/fleet-server-package-mbp.yml

JJBB for the specific MBP related to the packaging process and the snapshots generation
This is required to be able to implement the specific pipeline

jjbb: for the packaging only

---

main.go

To be merged on 8.1.1 release day just before the release.

Bump 8.1.2

---

main.go

Merge after the release of 8.1.2

Bump version to 8.1.3

---

internal/pkg/dl/enrollment_api_key_integration_test.go

See https://github.com/elastic/fleet-server/issues/1289 for more details
- Relates https://github.com/elastic/fleet-server/issues/1289

Flaky test enrollment_api_key_integration_test.go

---

main.go

Merge after the release of 7.17.3

Bump version to 7.17.4.

---

main.go

Merge after the release of 8.1.3

Bump 8.1.4

---

.ci/packaging.groovy

Cosmetic change to visualise the `DRA` stage in two stages:
- DRA snapshot
- DRA staging

ci: split dra meta-stage in two stages

---

main.go

Update to 8.2.1

---

.mergify.yml

Fixes branch protection for the automated PRs
Automate the approval with Mergify

mergify: auto-approve automated PRs

---

main.go

Update to 7.17.5

---

main.go

Update to 8.2.2

---

version/version.go

Update main to 8.4.0

---

main.go

Update to 8.2.3

---

.mergify.yml

Allow to backport using label to the 8.3 branch.

Fix mergify for 8.3.0

---

main.go

Update to 8.2.4

---

version/version.go

8.3.1 update

---

version/version.go

Update 8.3.2
Merge on release day.

Update to 8.3.2

---

version/version.go

Update main branch to 8.5.0

---

version/version.go

Updates references to the new release 8.3.4.
Merge after the release 8.3.3.

[Release] Update version to 8.3.4

---

version/version.go

Updates references to the new release 8.4.1.
Merge after the release 8.4.0.

[Release] Update version to 8.4.1

---

main.go

Update version to 7.17.7

---

version/version.go

Updates references to the new release 8.4.2.
Merge after the release 8.4.1.

[Release] Update version to 8.4.2

---

.ci/packaging.groovy

Fix migration to fleet-ci 
Caused by https://github.com/elastic/fleet-server/pull/1199

Fix gcs credentials for packaging

---

version/version.go

Updates references to the new release 8.4.3.
Merge after the release 8.4.2.

[Release] Update version to 8.4.3

---

internal/pkg/dl/migration.go

Add extra protection against accessing null fields to 8.5 migration

---

version/version.go

Updates references to the new release 8.4.4.
Merge after the release 8.4.3.

[Release] Update version to 8.4.4

---

version/version.go

Just a bump up version to 8.6 as in main

updated version to 8.6

---

main.go

Updates references to the new release 7.17.8.
Merge after the release 7.17.7.

[Release] Update version to 7.17.8

---

version/version.go

Updates references to the new release 8.5.1.
Merge after the release 8.5.0.

[Release] Update version to 8.5.1

---

.github/PULL_REQUEST_TEMPLATE.md

Add a section outlining the high level design considerations that must be included with any change to fleet server.

Add fleet-server design checklist to PR template

---

version/version.go

Updates references to the new release 8.5.2.
Merge after the release 8.5.1.

[Release] Update version to 8.5.2

---

version/version.go

Updates references to the new release 8.5.3.
Merge after the release 8.5.2.

[Release] Update version to 8.5.3

---

main.go

Updates references to the new release 7.17.9.
Merge after the release 7.17.8.

[Release] Update version to 7.17.9

---

NOTICE.txt

does what it says in the tin.
Otherwise the make check fails

chore: update new year 2023

---

version/version.go

Updates references to the new release 8.6.2.
Merge after the release 8.6.1.

[Release] Update version to 8.6.2

---

main.go

Updates references to the new release 7.17.10.
Merge after the release 7.17.9.

[Release] Update version to 7.17.10

---

.ci/bump-elastic-stack-snapshot.yml
.github/workflows/bump-elastic-stack-snapshot.yml

Fixes the bump automation by allowing running in parallel all the bump for all the active branches
Fixing the regex group that somehow remove the major...

updatecli: fix the bump elastic stack

---

.ci/Jenkinsfile
Makefile
README.md

Build and release the fleet-server docker image.
Added into the `.ci/Jenkinsfile` job, the stage/steps needed to build and push the fleet-server docker image:
- It creates a new docker image for each commit in main
- If there is no git tag pushed, that image is re-tagged as latest and pushed.
- If Jenkins runs because of a git tag is pushed, the image built is tagged with the git tag and pushed.
~As mentioned [in this comment](https://github.com/elastic/fleet-server/issues/2352#issuecomment-1475921796) it has been updated the docker image to be: 
`docker.elastic.co/fleet-server/fleet-server`~
In this first stage, the docker image used is `docker.elastic.co/observability-ci/fleet-server`
Example of this new stage run in a dry-run mode: …

Add stage to publish fleet-server docker image

---

version/version.go

Updates references to the new release 8.7.1.
Merge after the release 8.7.0.

[Release] Update version to 8.7.1

---

catalog-info.yaml

…file
This PR creates the Component resource for the fleet-server repository to be used by the Backstage
This PR doesn't affect anything. The data for this PR from the Backstage system
Related to the issue https://github.com/elastic/fleet-server/issues/2517

Add component entity to Backstage

---

fleet-server.reference.yml

Add fleet-server.reference.yml with all possible config options

Add fleet-server.reference.yml

---

.buildkite/pull-requests.json

This PR creates the Pull Request/Build configuration for the Buildkite CI system
It defines PR/build rules for the Buildkite CI system
Related to https://github.com/elastic/fleet-server/issues/2517

add .buildkite/pull-requests.json file

---

NOTICE.txt
go.mod
go.sum
internal/pkg/server/agent.go
internal/pkg/server/agent_test.go

upgrade elastic-agent-client lib to v7.1.1
improves ability to debug by using the gzipped pprof data instead of the text data in the pprof endpoints.  This improves our ability to debug.
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)~~
- Relates elastic/elastic-agent-client#69
- Relates elastic/elastic-agent#2530

upgrade elastic-agent-client to 7.1.1 for pprof fix

---

.github/workflows/build.yml
.github/workflows/sonarcloud.yml
Makefile
sonar-project.properties

This PR adds:
- sonar-project.properties that contains sonar settings
- update Makefile unit test to add coverage
- add Github action to generate sonar reports

Merge sonar project properties and unit coverage target

---

README.md

Add SonarCube code coverage badge

Add sonarqube code coverage badge

---

changelog/8.8.0.yaml

Add the 8.8.0 changelog
- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~
-

docs: add 8.8.0 changelog

---

version/version.go

Updates references to the new release 8.8.1.
Merge after the release 8.8.0.

[Release] Update version to 8.8.1

---

.buildkite/pipeline.yml
.buildkite/scripts/e2e_test.sh

Add `make test-e2e` target into buildkite pipeline

Add E2E test step to buildkite

---

version/version.go

Updates references to the new release 8.8.2.
Merge after the release 8.8.1.

[Release] Update version to 8.8.2

---

catalog-info.yaml

This PR adds the current dependencies related to CI/CD.
This PR adds the dependency with:
- [package-registry repository](https://github.com/elastic/package-registry/)
- pipeline to release a new distribution image when a tag is pushed - [link](https://github.com/elastic/package-registry/blob/main/.buildkite/release-package-registry-distribution.yml)
Documentation about these Backstage relationships: https://backstage.io/docs/features/software-catalog/well-known-relations/#dependson-and-dependencyof

Update dependencies in Component

---

main.go

Updates references to the new release 7.17.12.
Merge after the release 7.17.11.

[Release] Update version to 7.17.12

---

.buildkite/pipeline.service-tests.yml
.buildkite/pipeline.test-dev.yml
.buildkite/pipeline.test-qa.yml
catalog-info.yaml

Start setting up pipeline to run e2e tests from serverless.
Work during Ingest offiste.
Following the guide https://docs.elastic.dev/serverless/quality-gates#service-test-buildkite-pipeline
And try to add a pipeline to trigger with [run-bk-pipeline](https://github.com/elastic/serverless-gitops/blob/9467e7e72588d875ead88bbff6fe955a377b670c/common/workflows/run-bk-pipeline.yaml#L14-L20) workflow

added pipeline with e2e tests

---

catalog-info.yaml

Fix failing pr builds.
Tweak fleet-server-tests pipeline to only run on main branch

disable fleet-server-tests on prs

---

.buildkite/pipeline.yml

This PR is a followup of https://github.com/elastic/fleet-server/pull/2748 that will update the config with the correct image tag.
The image tag it's trying to update does not exist. Note that since Jenkins is building the image instead of buildkite, the tag has to be explicitly defined at the moment, but it should be defined on top. I did not do this, because i did not want to affect other peoples work.

push the correct image tag

---

.buildkite/hooks/post-checkout
.buildkite/pipeline.yml

PR solves the defining of the variable GO_VERSION
Manual defining in the pipeline.yml
The Buildkite pipeline will be triggered by this PR and we will see the result

fix go version

---

.buildkite/pipeline.yml

The stack components are using an old pipeline to update the controller config. Now, serverless gitops supports this functionality.
https://elasticco.atlassian.net/browse/TLS-446
Enable gpctl directly.
One can tests through buildkite like this:
https://buildkite.com/elastic/gpctl-promote/builds/4193
which triggered:
https://argo-workflows.us-central1.gcp.qa.cld.elstc.co/workflows/argo-events/gpctl-ci-9xsj2?tab=workflow&sidePanel=logs
and the service entry was updated:
https://github.com/elastic/serverless-gitops/commit/7d48117d659b81b5a68755bd5cbd2bdd885592fa

[TLS-446] use gpctl to update image tag using gpctl-promote

---

main.go

Updates references to the new release 7.17.13.
Merge after the release 7.17.12.

[Release] Update version to 7.17.13

---

main.go

Updates docs versions to 7.17.13.
Merge before the final Release build.

docs: update docs versions 7.17.13

---

.buildkite/scripts/dra_release.sh

Fix the issue with running dra-release script
https://buildkite.com/elastic/fleet-server-package-mbp/builds/228#0189924f-9155-4343-aeb1-b22128669e57
add `cd` command to change the current folder

hot-fix rda-release script

---

.buildkite/scripts/dra_release.sh
.buildkite/scripts/package.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/230#018992bc-5d99-45b7-8296-732f9bc7fc7b
define the FOLDER variable

add export FOLDER and export OUTPUT_FILE

---

.buildkite/scripts/package.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/232#018993cb-aa77-4e4a-acfe-61749eb103fa
change the variable MATRIX_TYPE to TYPE

fix package type var

---

.buildkite/pipeline.package.mbp.yml
.buildkite/scripts/common.sh
.buildkite/scripts/dra_release.sh
.buildkite/scripts/package.sh
.buildkite/scripts/release-manager.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/243#01899728-193d-4876-bc11-8bcbf84dab9a
changed the folder location
temporary, for test purposes, commented conditions for `DRA snapshot` and `DRA release staging` stages

debug the release-manager script

---

.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/scripts/release-manager.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/255#0189983a-8dc7-4471-90de-6b414cd799b5
changed the VAULT fields

change VAULT secrets

---

.buildkite/pipeline.yml

Trying to fix package step by using the same condition as docker public step [here](https://github.com/elastic/fleet-server/pull/2815/files)

fix package step

---

version/version.go

Updates references to the new release 8.9.2.
Merge after the release 8.9.1.

[Release] Update version to 8.9.2

---

.buildkite/pipeline.yml

Remove the depending step as it does not exist in 7.17

Update pipeline.yml to remove a non existing step

---

.buildkite/pipeline.yml

https://elasticco.atlassian.net/browse/TLS-626
We have bundled the e2e tests with the gpctl pipeline.

TLS-626 make sure e2e tests are being triggered before updating gitops

---

.buildkite/pipeline.tests-qa.yaml
.buildkite/pipeline.tests-staging.yaml

Add scale tests as fleet-server quality gate.
Added o11y quality gates
Trigger scale tests from fleet-server-tests
N/A

trigger scale tests from fleet-server-tests

---

main.go

Updates references to the new release 7.17.14.
Merge after the release 7.17.13.

[Release] Update version to 7.17.14

---

version/version.go

Updates references to the new release 8.10.2.
Merge after the release 8.10.1.

[Release] Update version to 8.10.2

---

.buildkite/pipeline.tests-qa.yaml
.buildkite/pipeline.tests-staging.yaml

Wait 10m before executing quality gates
Similar to https://github.com/elastic/fleet-controller/pull/215

added 10m wait before quality gates

---

version/version.go

Updates references to the new release 8.10.3.
Merge after the release 8.10.2.

[Release] Update version to 8.10.3

---

internal/pkg/api/server.go
internal/pkg/bulk/opRead.go
internal/pkg/bulk/opSearch.go
internal/pkg/coordinator/monitor.go
internal/pkg/monitor/monitor.go
internal/pkg/scheduler/scheduler.go

Serverless quality gates started failing since disabling debug logs: https://github.com/elastic/fleet-controller/pull/219
Modify most common error logs, and turning them to warn if matching the error message around ES not being available/DNS not ready.
Increased retry delay in monitor.

turn down error logs in serverless

---

.buildkite/pipeline.tests-production.yaml

When doing a promotion/rollback, it would be nice to do a basic check of prod error logs, etc.
Added basic quality gates to prod.

added basic quality gates to prod

---

internal/pkg/api/handleEnroll.go

Update enrollment logs

---

changelog/fragments/1696506127-context-canceled-error.yaml
internal/pkg/api/error.go

SLOs alerts are being triggered because of false 503 errors.
Change context canceled errors to 499, like the proxy does it. 
Enroll an agent and terminate the process during checkin/enroll. Verify that a 499 error is logged.
Closes https://github.com/elastic/fleet-server/issues/3010

changed context canceled to 499

---

internal/pkg/api/handleEnroll.go

updated log

---

main.go

Updates references to the new release 7.17.15.
Merge after the release 7.17.14.

[Release] Update version to 7.17.15

---

.buildkite/pipeline.tests-production-canary.yaml
.buildkite/pipeline.tests-staging.yaml

Add quality gates for production canary.
Also add baking period for staging and production:
* 30 minute for staging
* 1h for production canary

[Fleet] Quality gates for production canary

---

version/version.go

Updates references to the new release 8.10.5.
Merge after the release 8.10.4.

[Release] Update version to 8.10.5

---

changelog/fragments/1698163014-apm-errors.yaml
internal/pkg/api/error.go
internal/pkg/bulk/engine.go

This makes it easier to find the reason a transaction failed by capturing error events with the APM agent which will show up in the APM UI.

Send errors in API calls and bulker flushes to APM

---

go.mod
go.sum
internal/pkg/api/handleCheckin.go
internal/pkg/model/ext.go
testing/go.mod
testing/go.sum

Fix parsed policy mutation issue inadvertently added as part of #3048 that @nchaulet found.
Clone policy data before doing any operations that alter parsed policy references, serialize and return cloned data.

Fix mutation issue when using parsed policies

---

version/version.go

Updates references to the new release 8.11.1.
Merge after the release 8.11.0.

[Release] Update version to 8.11.1

---

main.go

Updates references to the new release 7.17.16.
Merge after the release 7.17.15.

[Release] Update version to 7.17.16

---

internal/pkg/api/api.go

rollback failure log change to info

---

internal/pkg/bulk/bulk_remote_output_test.go

Use nop loggers to fix some test failures.
Some tests that not fixed by #3138 are failing, see [the build](https://buildkite.com/elastic/fleet-server/builds/2598#018c26f6-64a8-48c5-aeea-402a774a78c7)
- Relates #3134

Use nop loggers to prevent test failures

---

main.go

Updates references to the new release 7.17.17.
Merge after the release 7.17.16.

[Release] Update version to 7.17.17

---

dev-tools/integration/.env

Use pinned version. Otherwise, if breaking changes in the upstream, it will affect the whole project.
It was reverted accidentally, see https://github.com/elastic/fleet-server/pull/3154#discussion_r1425496027

chore: use pinned versions

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-3faaf80d-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7210724235">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.0-3faaf80d-SNAPSHOT

---

.github/workflows/bump-elastic-stack-snapshot.yml

Similarly done in https://github.com/elastic/fleet-server/pull/3157
Notify the right team if the automation failed
Setting the new channel

ci(action): change slack notification channel

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-ubdkmnyz-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7259835767">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-ubdkmnyz-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-bde01754-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7259835767">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.0-83badc78-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-152634ef-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7289825269">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.0-cf3c9e0f-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-9amqxdis-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7289825269">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-yufkxnwm-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-67b59f94-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7330557659">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.0-01443900-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-vqaxdghw-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7330557659">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-qvykcic3-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-e8c03076-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7398912560">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.0-2335225c-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-a87bc5c4-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7411216760">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.0-a87bc5c4-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-ybxdr713-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7411216760">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-ybxdr713-SNAPSHOT

---

internal/pkg/api/handleAck.go

Fleet service quality gates in staging often fail with too high error log percentage.
Found that many errors logs are generated when an API key is not found (404). Making this error log a warning instead, as it is not a real service issue.

failed to read api key roles warn log

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-8upz6ftd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7490634978">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-u5089rwg-SNAPSHOT

---

README.md

Adds link to https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/dev_docs/developing_kibana_and_fleet_server.md to Fleet Server README.
Documents dev environment for contributing to Kibana + Fleet Server at the same time.

Add Kibana + Fleet Server dev guide link to README

---

NOTICE.txt
go.mod
go.sum

Update elastic-agent-libs to v0.7.4

Update elastic-agent-libs to v0.7.4

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-9yo2ylny-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7543527698">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-sq0d327c-SNAPSHOT

---

version/version.go

Updates references to the new release 8.12.1.
Merge after the release 8.12.0.

[Release] Update version to 8.12.1

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-knq1zsti-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7571938907">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-knq1zsti-SNAPSHOT

---

main.go

Updates references to the new release 7.17.18.
Merge after the release 7.17.17.

[Release] Update version to 7.17.18

---

.buildkite/hooks/pre-command
.buildkite/pipeline.yml
.buildkite/scripts/common.sh

It needs to remove the current GCP ci-bucket for DRA artifacts
1. Added a new bucket usage
2. Changed the credentials for GCP access
https://github.com/elastic/fleet-server/issues/3240

migrate DRA gcp bucket

---

.buildkite/hooks/pre-command
.buildkite/scripts/common.sh
dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.0-k08v7bga-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7713182304">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.1-lipljxnp-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.1-3x3y2wtd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7728079297">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.1-3x3y2wtd-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-l5snflwr-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7698124531">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-yil7wib0-SNAPSHOT

---

version/version.go

Updates references to the new release 8.12.2.
Merge after the release 8.12.1.

[Release] Update version to 8.12.2

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.1-jqpgs5zc-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7801745979">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.1-6b6cce09-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.1-135756ae-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7845817853">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.2-ae12c9ba-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-7ecbd6a2-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7845817853">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-4cf79044-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.2-c93a0352-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7888500941">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.2-5f8ffc93-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.2-4fee8a94-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7975583628">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.2-0bde1b22-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.2-bf518ba4-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7991169271">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.2-bf518ba4-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-e2cda7bd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7991169271">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-8dc05a81-SNAPSHOT

---

internal/pkg/api/server_test.go

Skip flakey subtest

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-772867d3-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7991169271">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-466f28cb-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-c44bedb9-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8006593080">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-c44bedb9-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-74a79bf3-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8006593080">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-74a79bf3-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-6775ba34-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8021124412">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-6775ba34-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-d7334334-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8021124412">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-d7334334-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.2-5482c56d-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8021124412">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.2-5482c56d-SNAPSHOT

---

version/version.go

Updates references to the new release 8.12.3.
Merge after the release 8.12.2.

[Release] Update version to 8.12.3

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-e73731dc-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8113133157">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-67f2fee7-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.2-af81666c-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8113133157">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-3f627ed1-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-496ca828-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8113133157">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-14244116-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-34a49bd9-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8190308516">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-863a113a-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-4d8adddd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8190308516">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-39cea920-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-07946972-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8235092852">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-6815ad42-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-50b2cd56-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8235092852">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-00a3f705-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-b9699c81-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8235092852">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-8783136e-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-98aa2390-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8251149311">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-98aa2390-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-faa2d2d3-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8251149311">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-faa2d2d3-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-72b525a7-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8251149311">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-72b525a7-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-530f08ed-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8266939147">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-530f08ed-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-e56dde0a-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8266939147">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-e56dde0a-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-b687dccd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8298281101">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-099ad3d3-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-fec1a044-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8298281101">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-068eda6a-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-bd8c2be5-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8298281101">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-a2d5464c-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-09a11c1c-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8328909248">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-09a11c1c-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-38b17954-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8328909248">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-38b17954-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-a9fbad89-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8328909248">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-a9fbad89-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-892adbf2-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8345407664">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-892adbf2-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-de4951fb-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8345407664">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-de4951fb-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-ef3d6214-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8345407664">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-ef3d6214-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-f215049e-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8361219645">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-f215049e-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-14d688f1-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8361219645">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-14d688f1-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-32b2aea6-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8361219645">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-32b2aea6-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-c03b2a22-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8377233426">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-c03b2a22-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-0321523b-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8392359920">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-0321523b-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-11aed950-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8392359920">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-11aed950-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-4e9e4428-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8422295218">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-4e9e4428-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-72a3bf67-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8422295218">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-72a3bf67-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.12.3-96ef37fe-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8422295218">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.12.3-96ef37fe-SNAPSHOT

---

version/version.go

Updates references to the new release 8.13.1.
Merge after the release 8.13.0.

[Release] Update version to 8.13.1

---

main.go

Updates references to the new release 7.17.20.
Merge after the release 7.17.19.

[Release] Update version to 7.17.20

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-433ba96e-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8438262875">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-433ba96e-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-7d0b3a7e-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8454040269">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-7d0b3a7e-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-3267fa9f-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8469385824">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-3267fa9f-SNAPSHOT

---

version/version.go

Updates references to the new release 8.13.2.
Merge after the release 8.13.1.

[Release] Update version to 8.13.2

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-4ba2d6fa-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8509731820">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.1-6f55db03-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-cca51f6c-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8509731820">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-20c1806a-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-f2b0327c-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8541054443">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-f2b0327c-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.2-765b9793-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8571847733">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.2-fcd9deb3-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.2-948b05e8-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8602406481">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.2-948b05e8-SNAPSHOT

---

version/version.go

Updates references to the new release 8.13.3.
Merge after the release 8.13.2.

[Release] Update version to 8.13.3

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-12492c7b-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8648973571">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-540ac545-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-19734ad9-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8691516091">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-19734ad9-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-cf1b0234-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8691516091">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-cf1b0234-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-b68daf90-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8708003338">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-b68daf90-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-3dc31fcb-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8724289821">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-3dc31fcb-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-318ae53b-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8740306549">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-318ae53b-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-c9047748-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8740306549">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-c9047748-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-c3270b70-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8786383490">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-22bed9d1-SNAPSHOT

---

NOTICE.txt
go.mod
go.sum
testing/go.mod
testing/go.sum

Update elastic-agent-libs to v0.9.5

Update elastic-agent-libs to v0.9.5

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-94d3b00c-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8802755775">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-94d3b00c-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-6596e7ab-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8818822276">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-6596e7ab-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-1067ed11-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8818822276">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-1067ed11-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-055b54fd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8850341789">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-32f53a5b-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-fe6333ee-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8897130371">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-b1148041-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.3-dae2338c-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8911054731">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.3-dae2338c-SNAPSHOT

---

version/version.go

Updates references to the new release 8.13.4.
Merge after the release 8.13.3.

[Release] Update version to 8.13.4

---

main.go

Updates references to the new release 7.17.22.
Merge after the release 7.17.21.

[Release] Update version to 7.17.22

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-3eefdcff-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8941022952">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-3eefdcff-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-ef3549bd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8941022952">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-ba404a5d-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.4-cc6fca83-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/8941022952">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.4-cc6fca83-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-177234da-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9004131854">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-177234da-SNAPSHOT

---

version/version.go

Updates references to the new release 8.13.5.
Merge after the release 8.13.4.

[Release] Update version to 8.13.5

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-fd69f4fd-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9019303434">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-fd69f4fd-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-99ead9e9-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9034206500">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-99ead9e9-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-f94896f6-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9034206500">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-f94896f6-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-15ba0fb2-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9065269301">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-15ba0fb2-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-a2355063-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9081728972">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-a2355063-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-2d092d81-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9081728972">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-2d092d81-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-0e5b6971-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9081728972">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-0e5b6971-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-526ba7a5-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9098113703">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-526ba7a5-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-28857d3f-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9098113703">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-28857d3f-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-00171e66-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9098113703">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-00171e66-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-c0a6b373-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9114701472">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-c0a6b373-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-201eb198-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9114701472">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-201eb198-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-9593fdd6-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9130328982">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-9593fdd6-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-be62218d-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9130328982">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-be62218d-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-05470747-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9130328982">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-05470747-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-3f0620ae-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9160787040">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-3f0620ae-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.14.0-f5ce0819-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9160787040">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.14.0-f5ce0819-SNAPSHOT

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-1a872dbc-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9160787040">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-1a872dbc-SNAPSHOT

---

.github/workflows/bump-elastic-stack-snapshot.yml
.github/workflows/bump-golang.yml

Use GitHub secrets rather than Vault secrets.
GitHub secrets have been created, there is a linked PR to a private repository in this PR - in case someone wanna see this

github-actions: use GitHub secrets

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.15.0-73defe35-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9178749876">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.15.0-73defe35-SNAPSHOT

---

.github/workflows/bump-elastic-stack-snapshot.yml
.github/workflows/bump-golang.yml

Fixes the syntax for slack messages and remove the experimental
I ran the workflow manually using this feature branch and it created https://github.com/elastic/fleet-server/pull/3570

github-action: pass user/email for the github action bot

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.5-d5b1e962-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/9176935608">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.5-d5b1e962-SNAPSHOT

---

internal/pkg/api/server_test.go

Fix flaky mTLS tests by ensuring the server runs for 500ms without any errors before any interactions are made with it.
We also filter out context cancelation errors returned from server.Run so they are not checked and only validate no errors were returned after the wait group is done
- Closes #3266

Fix flaky cert tests

---

version/version.go

Updates references to the new release 8.14.1.
Merge after the release 8.14.0.

[Release] Update version to 8.14.1

---

version/version.go

Updates references to the new release 8.14.2.
Merge after the release 8.14.1.

[Release] Update version to 8.14.2

---

main.go

Updates references to the new release 7.17.23.
Merge after the release 7.17.22.

[Release] Update version to 7.17.23

---

NOTICE.txt
go.mod
go.sum

Updating github.com/elastic/beats dependency to latest 7.x release

---

internal/pkg/monitor/subscription_monitor.go

Remove logging out `hits` in log message.

Fix log message

---

.buildkite/hooks/pre-command

DRA publishing always skipped due to new token permissions
Fix curl command to be available for new PAT generated token
- Relates https://github.com/elastic/ingest-dev/issues/3726

Fix-DRA-curl-command

---

.buildkite/hooks/pre-command

- Enhancement
Adding --fail flag to curl command to prevent silent returning of response with error 400 or above
--fail flag will return error if response is >=400
- https://github.com/elastic/ingest-dev/issues/3726

Adding fail catch to curl command

---

version/version.go

Bump version to 9.0.0

---

.mergify.yml

We have agreed to use `backport-<major>.<minor>` GitHub labels rather than `backport-<major>.<minor>.0` so the same GH label strategy works for the ingest and observability projects.
I decided to keep the current minor versions with the support for both labels.

mergify: support for backport-major.minor

---

.mergify.yml

Allow mergify to exclude backport-8.x if backport-skip is added.
See https://github.com/elastic/elastic-agent/pull/5521

mergify: avoid label automation always

---

version/version.go

Reverting 8.16.0 version bump

---

.github/workflows/bump-elastic-stack-snapshot.yml
.github/workflows/bump-golang.yml

gh-actions: support 2.0 slack that contains a breaking change and the signature changed

---

.buildkite/scripts/release-manager.sh
.buildkite/scripts/test-release.sh
Makefile
dev-tools/common.bash

Fix code smells found while working on https://github.com/elastic/fleet-server/pull/4318
Remove arch 386 targets
Rename docker build image to avoid confusion
group docker vars
fix gvm install on non linux/amd64 hosts
remove unused common.sh funcs
- ~~I have made corresponding change to the …

Cleanup various code smells withing Makefile ands supporting scripts

---

catalog-info.yaml

Add pagerduty service ID as per SRE recommendation.

Update catalog-info.yaml to comply with SRE recommendation

---

internal/pkg/testing/certs/certs.go

Tests ran with `GODEBUG=fips140=only` will panic due to CA SubjectKeyId generation using SHA1 by default.
Populate SubjectKeyId with value generated by other algorithm; copied implementation from https://github.com/elastic/elastic-agent-libs/pull/263
`GODEBUG=fips140=only gotip test ./...`
- …

Change CA generation in tests to avoid using SHA1

---

.buildkite/hooks/pre-command

Set BUILDKITE_ANALYTICS_TOKEN for FIPS E2E test step. Without this env var FIPS E2E step will break on CI
Include  FIPS E2E test step to the list of steps for which BUILDKITE_ANALYTICS_TOKEN will be set in pre-command hook.
- ~~[ ] I have ensured my design is stateless and will work when multiple fleet-server instances are behind a load balancer.~~
- ~~[ ] I have or intend to scale test my changes, ensuring it will work reliably with 100K+ agents connected.~~
- ~~[ ] I have included fail safe mechanisms to limit the load on fleet-server: rate limiting, circuit …

Add BUILDKITE_ANALYTICS_TOKEN in fips-e2e-test step

---

cmd/fleet/main.go
internal/pkg/action/token_resolver.go

Cleanup debug logs

---

catalog-info.yaml

run `7.17` DRA weekly to catch any breaking changes in the Unified Release before any releases.
- Run weekly instead of daily?

catalog-info: run 7.17 DRA weekly

---

.github/workflows/golangci-lint.yml

This PR bumps golangci-lint to v2.1.0 and fixes [the following issue ](https://github.com/elastic/fleet-server/actions/runs/14876904573/job/41775850396#step:5:21)
```
Error: Failed to run: Error: requested golangci-lint version 'v2.0.2' isn't supported: we support only v2.1.0 and later versions, Error: requested golangci-lint version 'v2.0.2' isn't supported: we support only v2.1.0 and later versions
at getRequestedVersion (/home/runner/work/_actions/golangci/golangci-lint-action/4afd733a84b1f43292c63897423277bb7f4313a9/dist/run/index.js:93373:15)
at getVersion (/home/runner/work/_actions/golangci/golangci-lint-action/4afd733a84b1f43292c63897423277bb7f4313a9/dist/run/index.js:93401:24)
at install (/home/runner/work/_actions/golangci/golangci-lint-action/4afd733a84b1f43292c63897423277bb7f43 …
```

ci: bump golangci-lint.yml

---

catalog-info.yaml

does what it says in the tin
After merging it

catalog-info: grant manage access to the CI robots team

---

.github/workflows/post-dependabot.yml

For third-party actions let's use pin versions
Pin the version

github-actions: use pinned version

---

.buildkite/pipeline.package.mbp.yml

22.04 is still under support https://en.wikipedia.org/wiki/Ubuntu_version_history
But 20.04 is under expanded security support

bk: use ubuntu 22.04

---

.mergify.yml

Tidy up the mergify configuration by honouring https://github.com/elastic/fleet-server/pull/4797
Removing duplicated configuration and references for the unused apmmachine

mergify: simplify and honour the defaults

---

catalog-info.yaml

Help our teams to manage builds whil eworking on adding new features to the CI

catalog-info: allow build CI jobs for observablt-ci-contractors

---

.buildkite/pipeline.yml

fix how FIPS image in bk is specified as it was missed in https://github.com/elastic/fleet-server/pull/5145

Use imagePrefix
