elastic/fleet-server

internal/pkg/model/schema.go
main.go
model/schema.json

Adds to the `schema.json` for the policy coordinator.
Adds `coordinator_idx` to `.fleet-policies` document. Renames `revision` to `revision_idx` so it matches the coordinator index, and make it clear it's an index.
Add `policy-leader` that will be in `.fleet-policies-leader` index to mark which Fleet Server is the current leader of a policy.

Add to the schema for coordinator

---

cmd/fleet/handleCheckin.go
cmd/fleet/main.go
cmd/fleet/server.go
cmd/fleet/server_test.go
internal/pkg/dl/constants.go
internal/pkg/dl/enrollment_api_key.go
internal/pkg/es/client.go
internal/pkg/esboot/bootstrap.go
internal/pkg/esboot/mapping.go
internal/pkg/esboot/migrate.go
internal/pkg/model/schema.go
internal/pkg/profile/profile.go
internal/pkg/runner/runner.go
model/schema.json

* Add enrollment API key definition into the schema
* Add migration code for development that migrates the keys from .kibana
index into .fleet-enrollment-api-keys index
This PR is based on my previous PR that is still pending review, so this one contains the commit from that PR. So only commits after the first one are directly related to this change.

Add enrollment API key definition into the schema

---

internal/pkg/config/config_test.go
internal/pkg/config/output.go
internal/pkg/config/output_test.go

Adds X-elastic-product-origin header to all the requests to elasticsearch.
This eliminates the Warning header from Elasticsearch responses while querying against .fleet-* indices, 
where otherwise you would get:
```
299 Elasticsearch-8.0.0-SNAPSHOT-5859c4d6e62606428c2e49a181c7f845cadabecb "this request accesses system indices: [.fleet-actions], but in a future major version, direct access to system indices will be prevented by default"
```

Add fleet X-elastic-product-origin header

---

.ci/Jenkinsfile
.ci/scripts/install-docker-compose.sh
Makefile

Enable the ITs in the CI
It was commented since there was a dependency to upgrade the required docker-composer version in the CI workers.

[CI] Enable integration tests

---

cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/schema.go

Remove agent saved object from enrollment code completely. With this change the agent is not going to appear in kibana upon enrollment anymore until kibana switched to the new indexes.
This allows to test at scale fairly (without double saving into .kibana as before)

Remove agent saved object from enrollment code completely

---

internal/pkg/dl/actions_integration_test.go
internal/pkg/monitor/monitor.go
internal/pkg/monitor/monitor_integration_test.go
internal/pkg/testing/actions.go

* Improve monitor: check the global checkpoint stats only when the
changes detected. Before it was checking global checkpoint first. Now
it executes the small query on the index to detect that the new
documents were indexed first. If the new document is detected then it
checks for the global checkpoint. After that the documents are
queried as before, capped by the global checkpoint value. This is
better that pulling large index stats document every second.
* Create integration tests for the monitor.
* Move the helpers for random actions creation/initialization into
"testing" package since, they are now shared between actions
integration tests and the monitor integration tests.

Improve index monitor logic. Add integration tests.

---

cmd/fleet/handleAck.go
cmd/fleet/handleCheckin.go

Fix the action ids. The action document id was used for the action id instead of the uuid action id.
Actions results before the change:
Actions results after the change:

Fix actions ID

---

cmd/fleet/main.go
dev-tools/integration/main.go
internal/pkg/action/dispatcher.go
internal/pkg/esboot/datastream.go
internal/pkg/esboot/esutil.go
internal/pkg/esboot/index.go
internal/pkg/esboot/template.go
internal/pkg/monitor/monitor.go
internal/pkg/monitor/subscription_monitor.go
internal/pkg/monitor/subscription_monitor_integration_test.go
internal/pkg/policy/monitor_test.go
internal/pkg/saved/crud.go

* Refactor index monitor. 
* Extract the simple monitor and subclass the subscription monitor from it 
that preserves the same interfaces and behavior as before.
* Use the simple monitor for agents actions since it is more efficient and avoids some the issues I listed below.
@blakerouse
I think there are few problems with the latest subscription monitor changes:
1. The callbacks firing each call with the new go routine. 
Depending on the timing of the go scheduler the order in which the go routines are fired is not predictable. This kind of an edge case since the monitor poll interval is 1 sec, and most likely your go routine will be scheduled within that time, but it's still fragile.
2. The tracking of the sequence number was not quite correct. 
It was advanced before the notifications …

Refactor index monitor.

---

internal/pkg/policy/monitor.go
internal/pkg/policy/monitor_test.go

This addresses the policy monitor defect that lead to intermittent failures in CI environment as described in 
https://github.com/elastic/fleet-server/issues/48 
Enabled the test `TestMonitor_NewPolicyExists` back and added the test coverage for repro case.
Tests before the change, that shows the problem with delay in the monitor running go routine start:
Tests after the change:

Fix policy monitor, add test

---

.gitignore
README.md

This adds a note on how to pass in the encryption key to fleet-server to connect it to Elasticsearch. This is only temporary until changes were made in Kibana.
Additionaly the fleet-server.dev.yml was added to gitignore. This allows to have a local config file which is not checked in.

Add notes around encryption key usage

---

.gitignore
cmd/fleet/handleEnroll.go
dev-tools/package/Dockerfile
dev-tools/rpm/nfpm.yaml
fleet-server.yml
systemd/fleet.service

Sets the correct agent id in the local meta upon enrollment if the agent id was provided. Does modify the local meta if the agent was not provided. 
Eventually the agent id in the local meta should not be used and the doc id value on the agent document should be used everywhere instead.
The related horde fix for the agent ID was done here https://github.com/elastic/horde/pull/23

Fix the agent ID handling

---

cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
internal/pkg/apikey/apikey.go

The API key in the policy should be in the format `keyId:key` not base64 encoded this PR fix that.

[Fleet] Fix api key format for agent policy

---

cmd/fleet/handleEnroll.go

Set -1 for the newly create agent action_seq_no.
This covers the case of the very first agent action in the systen with doc seq_no 0, that would go undetected if the newly create agents start with the action_seq_no == 0.

Fix new agent sequence number

---

dev-tools/cherrypick_pr

Cherry-pick of PR #66 to 7.x branch. Original message: 
Adds the `dev-tools/cherrypick_pr` helper script to help cherrypick changes from `master` to `7.x` branches.
`7.x` branch is now created for release manager building, so we need to start backporting any changes to that branch.

Cherry-pick #66 to 7.x: Add cherrypick_pr dev-tools helper.

---

cmd/fleet/main.go
internal/pkg/coordinator/monitor.go
internal/pkg/esboot/bootstrap.go
internal/pkg/migrate/migrate.go
internal/pkg/monitor/monitor.go
internal/pkg/policy/monitor.go

The new package based approach installs the indices templates and ILM policies, but doesn't create the indexes. This change allows the fleet server to run if indexes do not exists without exiting with error.
The bootstrapping code is commented out now, expecting the bootstrap to happen from the integration package.
https://github.com/elastic/integrations/pull/544

Make Fleet Server components resilient if the indices do not exist

---

cmd/fleet/main.go
internal/pkg/esboot/bootstrap.go

Hide old bootstrap logic behind FLEET_ES_BOOT environment variable
There are still cases during development when you want to boostrap everything by the fleet, then should run the fleet-server with the flag.
```
FLEET_ES_BOOT=1 ./bin/fleet-server
```

Hide old bootstrap logic behind FLEET_ES_BOOT environment variable

---

cmd/fleet/handleCheckin.go
cmd/fleet/schema.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
internal/pkg/testing/actions.go
model/schema.json

Rename action input_id to input_type. Instead of integration input id that is generated every time by kibana, rely on more stable integration input type.
Related Fleet Server package change: https://github.com/elastic/integrations/pull/573

Rename action input_id to input_type

---

.gitignore
NOTICE.txt
cmd/fleet/main.go
cmd/fleet/server.go
cmd/fleet/server_integration_test.go
dev-tools/integration/wait-for-elasticsearch.sh
fleet-server.yml
go.mod
go.sum
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/fleet.go
internal/pkg/config/input.go
internal/pkg/config/logging.go
internal/pkg/config/output.go
internal/pkg/coordinator/monitor.go
internal/pkg/logger/logger.go
internal/pkg/policy/monitor.go
internal/pkg/policy/self.go
internal/pkg/policy/self_test.go
internal/pkg/status/reporter.go
internal/pkg/testing/retry.go

Adds communication back to the Elastic Agent when running in `--agent-mode`.
Waits to get the initial configuration from Elastic Agent before starting the actual `FleetServer`. On any updated configuration it reloads the `FleetServer`.
Reports the status of `Starting` until a policy for the Fleet Server is identified. Elastic Agent will use that status reporting to wait until it goes to `Healthy` to perform the enrollment of itself.
To coordinate the control of Fleet Server by Elastic Agent.

Add communication to Elastic Agent

---

.gitignore
NOTICE.txt
cmd/fleet/main.go
cmd/fleet/server.go
cmd/fleet/server_integration_test.go
dev-tools/integration/wait-for-elasticsearch.sh
fleet-server.yml
go.mod
go.sum
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/fleet.go
internal/pkg/config/input.go
internal/pkg/config/logging.go
internal/pkg/config/output.go
internal/pkg/coordinator/monitor.go
internal/pkg/logger/logger.go
internal/pkg/policy/monitor.go
internal/pkg/policy/self.go
internal/pkg/policy/self_test.go
internal/pkg/status/reporter.go
internal/pkg/testing/retry.go

Cherry-pick of PR #71 to 7.x branch. Original message: 
Adds communication back to the Elastic Agent when running in `--agent-mode`.
Waits to get the initial configuration from Elastic Agent before starting the actual `FleetServer`. On any updated configuration it reloads the `FleetServer`.
Reports the status of `Starting` until a policy for the Fleet Server is identified. Elastic Agent will use that status reporting to wait until it goes to `Healthy` to perform the enrollment of itself.
To coordinate the control of Fleet Server by Elastic Agent.

Cherry-pick #71 to 7.x: Add communication to Elastic Agent

---

cmd/fleet/handleCheckin.go
cmd/fleet/main.go
cmd/fleet/schema.go
internal/pkg/coordinator/monitor.go
internal/pkg/es/mapping.go
internal/pkg/esboot/bootstrap.go
internal/pkg/migrate/migrate.go
internal/pkg/model/schema.go
internal/pkg/monitor/monitor.go
internal/pkg/policy/monitor.go
internal/pkg/testing/actions.go
model/schema.json

Cherry picked changes on master that were not backported to 7.x branch since the branch was created, missed the memo.

Cherry pick/master to 7.x

---

Makefile

Fixes issue where the .zip artifacts didn't contain fleet-server binary with the required `.exe` file extension.
So fleet-server can be executed and signed on Windows.

Add .exe extension to fleet-server windows artifacts.

---

Makefile

Cherry-pick of PR #78 to 7.x branch. Original message: 
Fixes issue where the .zip artifacts didn't contain fleet-server binary with the required `.exe` file extension.
So fleet-server can be executed and signed on Windows.

Cherry-pick #78 to 7.x: Add .exe extension to fleet-server windows artifacts.

---

internal/pkg/dl/actions.go
internal/pkg/model/schema.go
internal/pkg/monitor/monitor.go
model/schema.json

Backport to 7.x: 
https://github.com/elastic/fleet-server/pull/82

[Backport 7.x]: Reduce actions fetching interval if the full page of action documents was fetched

---

cmd/fleet/handleAck.go
cmd/fleet/schema.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Flattens .fleet-actions-results schema. 
The corresponding mapping change is done in the integration package
https://github.com/elastic/integrations/pull/672
The new action document for osquery
The new flattened .fleet-actions-results document

Flatten .fleet-actions-results schema

---

cmd/fleet/handleAck.go
cmd/fleet/schema.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Backport to 7.x of https://github.com/elastic/fleet-server/pull/87

[Backport 7.x] Flatten .fleet-actions-results schema

---

internal/pkg/config/config_test.go
internal/pkg/config/input.go

Changes the default TCP/IP port that the fleet server binds to from 8000 to 8220.
8000 is commonly used.  8220 is not.

Change default bind port from 8000 to 8220

---

internal/pkg/config/config_test.go
internal/pkg/config/input.go

[Backport 7.x]  Change default bind port from 8000 to 8220 (#92)

[Backport 7.x]  Change default bind port from 8000 to 8220 (#92)

---

cmd/fleet/server.go
cmd/fleet/server_integration_test.go
internal/pkg/config/input.go

Adds the ability to configure the TLS of the HTTP endpoint exposed by Fleet Server.
So Elastic Agent can configure and expose the Fleet Server over HTTPS.
- Relates #90

Add ssl configuration to fleet server http.

---

cmd/fleet/server.go
cmd/fleet/server_integration_test.go
internal/pkg/config/input.go

Cherry-pick of PR #98 to 7.x branch. Original message: 
Adds the ability to configure the TLS of the HTTP endpoint exposed by Fleet Server.
So Elastic Agent can configure and expose the Fleet Server over HTTPS.
- Relates #90

Cherry-pick #98 to 7.x: Add ssl configuration to fleet server http.

---

internal/pkg/monitor/global_checkpoint.go

Backport to 7.x of: https://github.com/elastic/fleet-server/pull/116

[Backport 7.x] Fix global checkpoint based monitoring 

---

cmd/fleet/handleAck.go
internal/pkg/dl/constants.go

Fixes issue where `.fleet-agents` `active` field is not set to `false` on un-enrollment. Without setting that field to `false` Kibana will still show the agent after successful un-enrollment.
So unenroll action works correctly.

Set agent active to false on unenroll

---

cmd/fleet/handleAck.go
internal/pkg/dl/constants.go

Cherry-pick of PR #118 to 7.x branch. Original message: 
Fixes issue where `.fleet-agents` `active` field is not set to `false` on un-enrollment. Without setting that field to `false` Kibana will still show the agent after successful un-enrollment.
So unenroll action works correctly.

Cherry-pick #118 to 7.x: Set agent active to false on unenroll

---

cmd/fleet/handleAck.go
cmd/fleet/server_integration_test.go
internal/pkg/apikey/auth.go
internal/pkg/apikey/create.go
internal/pkg/apikey/invalidate.go

Invalidates both API keys used by the Agent after un-enrollment.
So those API keys cannot be used any more.
- Closes #123

Add API key invalidation on unenroll ACK.

---

cmd/fleet/handleAck.go
cmd/fleet/server_integration_test.go
internal/pkg/apikey/auth.go
internal/pkg/apikey/create.go
internal/pkg/apikey/invalidate.go

Cherry-pick of PR #124 to 7.x branch. Original message: 
Invalidates both API keys used by the Agent after un-enrollment.
So those API keys cannot be used any more.
- Closes #123

Cherry-pick #124 to 7.x: Add API key invalidation on unenroll ACK.

---

internal/pkg/config/config_test.go
internal/pkg/config/fleet.go
internal/pkg/config/testdata/bad-logging.yml

Enable trace level logging.
Fleet Server has some useful trace level logs that are too noisy to surface to debug level.
The Elastic Agent would not be able to set the config lower than debug level, but this is still useful for development&diags when running Fleet Server standalone.

Enable trace level logging

---

internal/pkg/config/config_test.go
internal/pkg/config/fleet.go
internal/pkg/config/testdata/bad-logging.yml

Backport to 7.x: https://github.com/elastic/fleet-server/pull/112

Cherry-pick #112 to 7.x: Enable trace level logging (#112)

---

cmd/fleet/schema.go

Fixed the type incompatibility if the agent sends the event payload. Event payload is expected to be a json fragment.
For Osquerybeat this payload would need to be searchable, since it will contain the version of osqueryd binary for example.

Update Event payload type.

---

cmd/fleet/handleStatus.go
cmd/fleet/main.go
cmd/fleet/router.go
cmd/fleet/schema.go
cmd/fleet/server_integration_test.go
cmd/fleet/server_test.go
internal/pkg/policy/self.go

Adds an `/api/status` endpoint to verify that Fleet Server is running properly. This is also used by the Elastic Agent that it can communicate with a Fleet Server.
Elastic Agent verifies that it can communicate with a Fleet Server when a policy included an updated connection URL to a Fleet Server. Without this endpoint present then Elastic Agent will not accept and apply the policy because it cannot verify that the Fleet Server it needs to communicate with is correct.
This mirrors the `/api/status` URL by Kibana, so nothing needs to change in Elastic Agent. Elastic Agent can switch from a Kibana to Fleet Server without any custom logic.
- ~~[ ] I …

Add API status endpoint

---

cmd/fleet/handleStatus.go
cmd/fleet/main.go
cmd/fleet/router.go
cmd/fleet/schema.go
cmd/fleet/server_integration_test.go
cmd/fleet/server_test.go
internal/pkg/policy/self.go

Cherry-pick of PR #131 to 7.x branch. Original message: 
Adds an `/api/status` endpoint to verify that Fleet Server is running properly. This is also used by the Elastic Agent that it can communicate with a Fleet Server.
Elastic Agent verifies that it can communicate with a Fleet Server when a policy included an updated connection URL to a Fleet Server. Without this endpoint present then Elastic Agent will not accept and apply the policy because it cannot verify that the Fleet Server it needs to communicate with is correct.
This mirrors the `/api/status` URL by Kibana, so nothing needs to change in Elastic Agent. Elastic Agent can switch from a Kibana to Fleet Server without any custom logic.
- ~~[ ] I have made …

Cherry-pick #131 to 7.x: Add API status endpoint

---

cmd/fleet/auth.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/router.go
internal/pkg/cache/cache.go
internal/pkg/dl/artifact.go
internal/pkg/dl/constants.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
internal/pkg/throttle/throttle.go
internal/pkg/throttle/throttle_test.go
model/schema.json

The security app generates multiple user defined artifacts for delivery to the endpoint.  There is an existing implementation in Kibana to server up these artifacts via HTTPS.  With the introduction of Fleet Server, endpoints will no longer have credentials nor necessarily a route to Kibana.  As such, these artifacts must be served from Fleet Server instead.
Artifacts were previously stored in saved objects.  There is ongoing work in Kibana to move the records from saved objects into a dedicated .fleet-artifacts indice.  Fleet-Server and Kibana have agreed on a [schema](https://github.com/elastic/kibana/issues/90513#issuecomment-783684463).  In addition, there is an agreed upon URL format that Kibana will employ when generating a schema:
```
api/fleet/artifacts/:id/:sha2
```
This …

Handle artifact request from endpoint  

---

cmd/fleet/main.go
cmd/fleet/server_integration_test.go
cmd/fleet/server_test.go
internal/pkg/cache/cache.go
internal/pkg/config/cache.go
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/throttle/throttle_test.go

Adds optional configuration to tweak cache thresholds.  Tuned down the default configuration to minimize memory usage.
The server is expected to run in limited memory environments.
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
Modify the cache config section in the yaml, and restart server.
- 
- Closes https://github.com/elastic/fleet-server/issues/96

Add cache configuration option.

---

.mergify.yml

Enable [backports](https://docs.mergify.io/actions/backport.html) with [mergify](https://docs.mergify.io/index.html) for:
- 7.x branch with the label `v7.13.0`
- 7.12 branch with the label `v7.12.0`
If any conflicts the PRs are created with the label `conflict` in addition a comment will be added with the actions to be done in order to fix the conflicts locally and push to the branch.
`Mergify` provides different mechanism to interact with PRs and automate certain process.
Backports to 7.x -> https://github.com/elastic/apm-pipeline-library/pull/995
Merges to master -> https://github.com/elastic/apm-pipeline-library/pull/994
* Further details explained in https://github.com/elastic/beats/pull/24608
* There is an initiative to automate the GitHub labels creation in each obs11 repo -> …

Enable backport automation with mergify

---

.mergify.yml

Quote branches
Otherwise `mergify` will complain with the str format
```
The new Mergify configuration is invalid
expected str @ pull_request_rules → item 1 → actions → backport → branches → item 0
```

mergify: quote the branches

---

Makefile

Both darwin build modes fail on the linux build machines.  This is a temporary change until we can get the cross compile resolved.
Builds are currently broken due cross compile requirements for darwin.  This is a temporary work around.

Remove darwin/arm64 support.  Remove ASLR support for darwin.  

---

Makefile

Fix incorrect buildmode for arm64/darwin
Should build consistently using ASLR where possible.
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

Fix incorrect buildmode for arm64/darwin

---

cmd/fleet/main.go
fleet-server.yml
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go

Moves `cache` keys under the input so they can be set by the Elastic Agent. Disables the server profile by default.
So `cache` can be adjusted from the Fleet Server integration.
- Closes #155

Fix configuration for cache and server profiler off by default

---

.mergify.yml

Auto-merge backports for 7.x and 7.12 branches only if:
- CLA success
- CI success
Auto-merge based on `squash-merge`
No more manual actions for backports
@blakerouse asked about the auto-merge so this is the proposal

[mergify] auto-merge backports

---

cmd/fleet/main.go
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go
internal/pkg/config/monitor.go
internal/pkg/monitor/monitor.go

Increases the monitor throughput:
* Increase the monitor fetch size to 1000 by default, the max number of documents fetched at once.
* Makes the monitor fetch size configurable.
* Decreased the pause between fetches from 50ms to 10ms.
Tuning of the throughput.

Increase the monitor throughput: increase the default fetch size, make it configurable.

---

NOTICE.txt
cmd/fleet/bulkCheckin.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
go.mod
go.sum
internal/pkg/action/dispatcher.go
internal/pkg/dl/constants.go
internal/pkg/model/schema.go
internal/pkg/sqn/sqn.go
model/schema.json

Changes the storage format of the .fleet-agents.action_seq_no to an array.
Sets up the Fleet Server to handle the new ES fleet API and the multi-shard configuration.

Change the agent.action_seq_no storage format from number to an array

---

internal/pkg/coordinator/v0.go
internal/pkg/dl/policies.go
internal/pkg/dsl/term.go

There was an issue where it was possible for the policy coordinator to get stuck because the leader election happened at the same time the coordinator was starting. It was possible that pushing onto the coordinator channel in `Run` would block forever because `Update` was called before the `Run` could start the `for` loop. This removes that logic and removes the requirement of a buffered channel.
There was also an issue where the `QueryLatestPolicies` would only return the first 10 policies. If you had more than 10 policies the 10+ where never picked up by Fleet Server. This increases the size to the maximum amount of 10000.
So policies will pass through the coordinator and be rolled out to Elastic Agents.
- ~~[ ] I have …

Fix issue with rolling out policies from the coordinator.

---

.mergify.yml

Use the free options
We don't use the premium version

mergify: priority is now a pro feature

---

NOTICE.txt
cmd/fleet/bulkCheckin.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
go.mod
go.sum
internal/pkg/action/dispatcher.go
internal/pkg/dl/constants.go
internal/pkg/model/schema.go
internal/pkg/sqn/sqn.go
model/schema.json

Cherry-pick of PR #174 to 7.x branch. Original message: 
Changes the storage format of the .fleet-agents.action_seq_no to an array.
Sets up the Fleet Server to handle the new ES fleet API and the multi-shard configuration.

Cherry-pick #174 to 7.x: Change the agent.action_seq_no storage format from number to an array

---

cmd/fleet/handleEnroll.go
internal/pkg/apikey/apikey.go
internal/pkg/apikey/apikey_integration_test.go
internal/pkg/apikey/apikey_test.go
internal/pkg/apikey/create.go
internal/pkg/apikey/get.go
internal/pkg/apikey/metadata.go

Adds metadata to they api keys.
```
"metadata" : {
"application" : "fleet-agent",
"agent_id" : "887f1001-5dc8-45e2-aa61-413123c8013b",
"type" : "access"
}
```
Not sure about the ```type``` field,  wanted to capture the possible values ```output``` and ```access```.
Maybe a better name? or can remove if not needed. @scunningham @ruflin 
P.S. If you are having issues running integration tests locally,  try delete the elasticsearch docker image and pull the latest one that implements the new api.
Adopting new ES Api https://github.com/elastic/elasticsearch/issues/48182 for 7.13.
- Closes https://github.com/elastic/fleet-server/issues/193

Implement support for API Key metadata

---

internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Add user_id to .fleet-actions schema, to reflect the addition of the field to the index in https://github.com/elastic/kibana/pull/95935

Add user_id to .fleet-actions schema

---

internal/pkg/bulk/bulk.go
internal/pkg/bulk/opt.go

The larger queues are more efficient at high scale, but are way overkill on small systems.
The memory usage at bootstrap and at scale was large given the default settings.  Scale down the default and make configurable.
Provides smaller boot footprint for tiny containers.

Move to less aggressive bulk queue preallocation size by default.

---

cmd/fleet/handleCheckin.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go

Adds optional gzip support if client asks for it.
Option to minimize response size.  Defaults to best speed.
- Closes https://github.com/elastic/fleet-server/issues/108
[scunningham@sgc-docker ~]$ cat /tmp/fleet.log   | grep response
{"level":"trace","level":9,"time":"Apr  5 17:02:32.109433","message":"Compressing policy response"}

Add optional gzip compression support on check-in response.

---

internal/pkg/dl/actions.go
internal/pkg/dl/policies_leader.go

Graceful handling for the case where the indices are not found.
Tested full stack with ES system indices plugin PR https://github.com/elastic/elasticsearch/pull/70689
and kibana update for this https://github.com/elastic/kibana/pull/96338 working end to end with osquerybeat.
Found issues where fleet server doesn't handle the case where the index doesn't exists.
The ES system indices plugin no longer creates the indices. The indices are now created when the first document is pushed, and the fleet server doesn't handle the missing index case gracefully (as some point before it did).
This change can be merged before the related tickets.
This is important in order to adopt the fleet system indices plugin.

Update graceful handling for missing indices to accommodate the new fleet system indices plugin

---

cmd/fleet/handleCheckin.go

Fixes #223 
So Elastic Agents can send events.
- ~~[] I have added tests that prove my fix is effective or that my feature works~~
- Closes #223

Fix issue with not sending the agents default api_key.

---

internal/pkg/coordinator/monitor.go

Fixes coordinator goroutine tight loop on cancelled context.
Addresses https://github.com/elastic/fleet-server/issues/220
- Closes https://github.com/elastic/fleet-server/issues/220

Fix coordinator goroutine tight loop on cancelled context

---

NOTICE.txt
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/metrics.go
cmd/fleet/server_test.go
cmd/fleet/userAgent.go
cmd/fleet/userAgent_test.go
fleet-server.yml
go.mod
go.sum

Adds checks to the enrollment and checkin API to ensure that the `User-Agent` header is correct for an Elastic Agent. This verifies that the version of the Elastic Agent is a support version.
This does allow an Elastic Agent to be on a higher patched version than the Fleet Server, but not higher on the MAJOR.MINOR.
Older Elastic Agents will not work correctly with new Fleet Server, so they need to not connect to the Fleet Server.
- Closes #238

Ensure that the connecting Elastic Agent is a supported version.

---

internal/pkg/monitor/monitor.go

Changed the fleet server monitor logging message level to debug for when the index is not found.
Improved a couple of more logging messages in the same scope.
Addresses https://github.com/elastic/fleet-server/issues/246
- Closes https://github.com/elastic/fleet-server/issues/246
proof that logging is at debug level:

Update fleet server monitor logging

---

cmd/fleet/main.go
internal/pkg/es/info.go
internal/pkg/ver/check.go
internal/pkg/ver/check_test.go

Adds validation for elasticsearch version, according to the spec https://github.com/elastic/fleet-server/issues/167#event-4612390369
This needs to be in 7.13 release.
- Closes https://github.com/elastic/fleet-server/issues/167
```
{"log.level":"debug","fleet_version":"8.0.0","@timestamp":"2021-04-19T16:46:33.903Z","message":"check version compatibility with elasticsearch"}
{"log.level":"debug","elasticsearch_version":"8.0.0","@timestamp":"2021-04-19T16:46:33.903Z","message":"fetched elasticsearch version"}
{"log.level":"info","fleet_version":"8.0.0","elasticsearch_version":"8.0.0","@timestamp":"2021-04-19T16:46:33.903Z","message":"versions are compatible"}
```

Validate Elasticsearch version for compatibility

---

cmd/fleet/main.go
example/fleet-server-100.yml
fleet-server.yml
internal/pkg/config/config.go
internal/pkg/config/input.go

Moves the runtime configuration item into the input section, so it is possible to configure via agent policy.  Otherwise, the feature cannot be configured except by local policy.
GC tweaking is necessary in the small memory platforms.
...
12:50:53.744 INF SetGCPercent new=20 old=100
...

Move runtime configuration so that can be configured via agent.

---

internal/pkg/es/fleet_global_checkpoints.go
internal/pkg/monitor/global_checkpoint.go

Adopts the Elasticsearch polling API change that now handles the waiting on index if it doesn't exists.
https://github.com/elastic/elasticsearch/pull/71890
ATTN!!! This PR integration tests will fail until the Elasticsearch docker images are updated with the corresponding ES change. Merging it before the change will break fleet server for a lot of good people out there.
The Fleet Server would poll every 3 secs for each monitored index until it is created otherwise.
This change reduces the number of http requests the Fleet Server would have to do to detect the very document in the index and let Eleasticsearch handle the wait.

Wait on index when polling global checkpoints

---

.mergify.yml

1) Only automerge for those backports with the `backport` label and PR's author `mergify[bot]`
2) Backports will add the `backport` label to help with the auto-merge.
Simplify the rules with the `~=` regex pattern -> https://docs.mergify.io/conditions/#grammar
Automerge only the backport

mergify: Automerge only the backport

---

internal/pkg/policy/self.go
internal/pkg/policy/self_test.go

Adds context to the `missing config fleet.agent.id` so its clear that is okay during bootstrap.
So its not reported as an error by users.

Improve log message about degraded being okay during bootstrap.

---

.mergify.yml

Since https://github.com/Mergifyio/mergify-engine/issues/2419 has been solved we can now change the title.
This is a proposal to change the title in the PRs that are backported with `mergify`.
`[target-branch](backport #1234) title`
Highlight what's important in the title to easily filter target branches
Similar to https://github.com/elastic/beats/pull/25396

[mergify] change title for the backports

---

internal/pkg/config/monitor.go
internal/pkg/monitor/monitor.go

* Reduces  the monitor long poll timeout to 4 minutes by default
* Change log message level from Error to Info 
This addresses https://github.com/elastic/fleet-server/issues/304
- Closes https://github.com/elastic/fleet-server/issues/304

Reduce the monitor long poll timeout to 4 minutes by default

---

.mergify.yml

Check that the name of "head" matches, rather than "base".
Otherwise the branches are not deleted

mergify: fix delete_head_branch condition

---

.ci/Jenkinsfile
Makefile
dev-tools/common.bash

This PR sets an environment variable on CI, reading this project's `.go-version` file and setting that value to `GO_VERSION`. Then, because the `withGoEnv` built-in step supports passing a version, we are using the new variable as an input parameter in the step. As a consequence, the step will internally use GVM to setup the Go environment for that version.
The PR also replaces Gimme with gvm, and finally uses the existing script to set the Go version in the execution of the tests.
We want to run the code in the proper version
- Discovered while testing #341
- Closes #345
I'd recommend moving to [`gvm`](https://github.com/andrewkroh/gvm) in the automation scripts, to match what the CI does. I did that in https://github.com/elastic/fleet-server/pull/346/commits/f888d11436c4773293da64a46a9e6 …

fix: use the right Go version in the CI

---

internal/pkg/bulk/opMulti.go

received..
Ok, this seems to be a problem with the int vs uint check that we do.
I am not sure why this was raised now / today. I event check older 1.15
version of golang and I had the same issue.
Before the fix
```
❯ make release-manager-snapshot                                                                                                                                                                                                    [22:46:57]
./dev-tools/run_with_go_ver /Applications/Xcode.app/Contents/Developer/usr/bin/make release
v0.1.0
GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s -X main.Version=8.0.0-SNAPSHOT" -buildmode=pie -o build/binaries/fleet-server-8.0.0-SNAPSHOT-darwin-x86_64/fleet-server .
GOOS=darwin GOARCH=arm64 go build -ldflags="-w -s -X …
```

Fix the comparison between a MaxUint32 and the len of the slice

---

cmd/fleet/handleCheckin.go
internal/pkg/logger/logger.go

Conforms the error field and the hash field in the logs to ECS.
Default is not ECS compliant and is breaking Elastic mapping.
- Relates https://github.com/elastic/fleet-server/issues/358
```
{"log.level":"info","status":"FAILED","@timestamp":"2021-05-17T13:54:46.491Z","message":"Error - dial tcp 127.0.0.1:9200: connect: connection refused"} …
```

Conform error and hash fields to ECS.

---

.ci/Jenkinsfile
Makefile

It creates a new stage in the CI pipeline separating the unit tests from the integration ones.
Finally, we renamed the jUnit output file to be consistent with the Make goal.
Separation of concerns. From a delivery pipeline stand point, we would like to differenciate the execution of the different test suite with the sole goal of providing fast feedback to the developers when problems occur. At the moment a unit test fails, the pipeline will display that information with a red flag in the unit tests stage, stopping the pipeline at that moment.
On the same hand, integration tests usually come with the preparation of third-party services (in this particular case in the way of docker-compose services) that could cost heavy amount of time/resources, and we want to delay that preparation until …

chore: separate unit tests from integration tests in CI pipeline

---

Makefile
cmd/fleet/main.go
internal/pkg/logger/logger.go
main.go

Adds the short form of the git commit id and the version to the boot message.
It remains difficult to know what specific version of code is installed in the cloud during beta cycles.  
This will allow the developer to examine the logs to figure out the specific version of the code used in the build. …

Log version and commit at boot

---

internal/pkg/apikey/invalidate.go

Sends owner: true on API call to invalid API keys.
So API keys can be invalidated when Fleet Server is connected to elasticsearch using the `elastic/fleet-server` service token.
- Closes #380

Send owner: true on API call to invalid API keys.

---

cmd/fleet/handleCheckin.go
cmd/fleet/schema.go
internal/pkg/checkin/bulk.go
internal/pkg/checkin/bulk_test.go
internal/pkg/dl/constants.go

Writes out the checkin status field to the last_checkin_status field in the agent record.  This is necessary to support UX changes.
UX needs it.
Setup local fleet server and point an agent at it.  You can validate field change using the dev tools in kibana.

Propagate checkin status to agent record

---

internal/pkg/logger/ecs.go
internal/pkg/logger/logger.go
internal/pkg/logger/zapStub.go

Promotes zap logger keys to top level.  Aligns with ECS.
The zap logger stub is necessary because some reused components in beats require it.  To conform with ECS, the fields logged through the zap stub must be at the top level.
Should see the new log lines on fleet server boot.  Only two lines are affected in initial boot.
- Closes https://github.com/elastic/fleet-server/issues/305
```
{"log.logger":"fleet-metrics.api","message":"Starting stats endpoint","log.level":"info","@timestamp":"2021-06-02T20:14:48.544Z"}
{"log.level":"debug","addr":["https://sgc-security-41.es.us-central1.gcp.qa.cld.elstc.co:9243"],"user":"elastic","maxConnsPersHost":128,"@timestam …
```

Remove zap stub logger bleed through.

---

cmd/fleet/auth.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/server.go
internal/pkg/apikey/apikey_integration_test.go
internal/pkg/apikey/auth.go
internal/pkg/apikey/get.go
internal/pkg/bulk/bulk_test.go
internal/pkg/bulk/engine.go
internal/pkg/bulk/opApiKey.go
internal/pkg/bulk/opt.go
internal/pkg/bulk/setup_test.go
internal/pkg/monitor/monitor.go
internal/pkg/testing/bulk.go
internal/pkg/testing/setup.go

1) Add bulk API key to bulk interface.  We don't have bulk api upstream, but this allows us to control the concurrence of the calls without having a separate pool.  When/If we get bulk calls, we can swap out transparently.
2) Refactor bulk engine startup.  Properly handle the case where the engine throws an error.
The ApiKey auth and create calls are slow; they are backing up and consuming all the connections to elastic search, starving the normal bulk api calls.
The bulk startup refactor was done largely to accommodate properly error handling when the bulk engine fails.  In addition, the process was not waiting for a clean shutdown on exit.
- [x ] I have …

Refactor bulk engine startup and add bulk ApiKey 

---

cmd/fleet/error.go
cmd/fleet/handleAck.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/server.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go
internal/pkg/config/limits.go

Enforces configurable max body size limits on payloads.
Differentiates between header and read timeout.
Returns a non-400 error on a read timeout.  Read timeouts are typically due to elasticsearch not responding to auth requests quickly.
Necessary to fortify server against attack.

Tweak server timeouts.  Limit body size to defend malicious agent

---

NOTICE.txt
cmd/fleet/auth.go
cmd/fleet/handleAck.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/server_integration_test.go
go.mod
go.sum
internal/pkg/apikey/apikey_integration_test.go
internal/pkg/apikey/create.go
internal/pkg/bulk/opApiKey.go
internal/pkg/cache/cache.go
internal/pkg/config/cache.go
internal/pkg/config/config_test.go

Makes the TTL values on the cache objects configurable.  Allows cache to be reconfigured without restarting the process.  Cache is dropped on reconfiguration.
Increate the TTL on the api key to 15m with optional jitter.   This is to work around latency issues at scale with validating API .  In addition, validate that 'enabled' flag on the agent during auth.   Between the 'enabled' flag, and the ability to drop the cache by reconfiguration in a break glass scenario, it seems minimize auth round trips to elastic.  This takes load off the fleet-server as well as elastic.
Also, cache the case when an api key is not valid.  This avoids roundtrip for an already disabled api key.
The server runs into issues at large scale while trying to validate many ApiKeys at once.  Particularly when a policy …

Configure cache

---

NOTICE.txt
cmd/fleet/auth.go
cmd/fleet/handleAck.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/server_integration_test.go
go.mod
go.sum
internal/pkg/apikey/apikey_integration_test.go
internal/pkg/apikey/create.go
internal/pkg/bulk/opApiKey.go
internal/pkg/cache/cache.go
internal/pkg/config/cache.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go
internal/pkg/config/timeouts.go

Adds an optional jitter to the long poll, defined as 30s by default.
Adding a bit of jitter helps smooth out load over time at scale. The server performs better if the load is spread out avoiding spikes, particularly as we add policy rollout, etc.
Test was run with 100k endpoints horde emulation, deploying at a rate of 20k per second.  This is a …

Add optional jitter to long poll

---

example/fleet-server-100.yml
internal/pkg/bulk/opt.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go
internal/pkg/config/output.go
internal/pkg/config/output_test.go

The elastic search section is an "output" section and has the side effect of being
applied to all agents when changed in Kibana.  The bulk section only applies to Fleet
Server so should be located in the input section configuration the server.
Moves the bulk config section around so more easily configurable in Kibana.
Previous location was not strictly correct and had operational side effect of being applied to every policy when changed in Kibana.
- [x ] I have added an entry in `CHANGELOG.next.asciidoc` or …

Move Fleet Server specific config from elastic search section to server section.

---

.ci/bump-go-release-version.sh
.ci/jobs/fleet-server.yml
.mergify.yml

Delegate the update for the go-version to be done automatically.
You can use this script locally:
```bash
.ci/bump-go-release-version.sh <new-go-version>
```
NOTE: it will add and commit the changes in the existing branch. The push and PR creation is not done within this script.
No more manual actions.
This automation will not merge the PR automatically, neither it will create any backports.
We do want the teams to do so:
- Review the changes and validate the CI status
- Create the relevant backports either with mergify or manually with some other tooling.
This particular automation will run on weekly basis. The pipeline is [bump-go-release-version-pipeline](https://apm-ci.elastic.co/job/apm-shared/job/bump-go-release-version-pipeline/)
```bash
$ .ci/bump-go-release-version.sh 1.16.6 …
```

Automate the go version update

---

Makefile
internal/pkg/coordinator/monitor.go
internal/pkg/coordinator/monitor_integration_test.go
internal/pkg/dl/agent.go
internal/pkg/dl/agent_integration_test.go
internal/pkg/dl/constants.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Adds an unenroller that automatically unenrolls agents when the policy has `unenroll_timeout` set and agents `last_checkin` timestamp is older than the defined timeout.
To support ephemeral Elastic Agent's, having the Elastic Agent's list automatically cleaned up.
- Closes #446

Add unenroller based on unenroll_timeout from policy

---

internal/pkg/config/output.go
internal/pkg/config/output_test.go

- Enhancement
Add `proxy_headers` setting to the output.elasticsearch configuration.
If proxy_disabled is not set, we will read the proxy settings from the environment variables HTTP_PROXY, HTTPS_PROXY, and NOPROXY.
Keep set of proxy settings in line with recent changes in Beats/Agent.
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding change to the default configuration files~~

Streamline proxy settings with Beats/Agent

---

internal/pkg/config/output.go
internal/pkg/config/output_test.go

Cherry-pick of PR #491 to 7.14 branch. Original message: 
- Enhancement
Add `proxy_headers` setting to the output.elasticsearch configuration.
If proxy_disabled is not set, we will read the proxy settings from the environment variables HTTP_PROXY, HTTPS_PROXY, and NOPROXY.
Keep set of proxy settings in line with recent changes in Beats/Agent.
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding change to the default configuration files~~

Cherry-pick #491 to 7.14: Streamline proxy settings with Beats/Agent

---

NOTICE.txt
cmd/fleet/server.go
go.mod
internal/pkg/limit/listener.go
internal/pkg/logger/ecs.go

…block.
Changes the logic around limiting connections.  Previous logic blocked on ACCEPT.  This causes a stall before TLS connection handshake will occur.  After a long enough stall, the connection will timeout on resumption anyhow.
The new implementation accepts all connections and closes if at max limit.  Close is logged at the Warn() level.
Previous implementation had no direct visibility when server was hitting the mx limit.  It is critical that the customer has direct indication when they are either misconfigured  or being attacked.
- [x ] I have added tests that prove my fix is …

Modify hard connection limiter to Close connection on max instead of block.

---

Makefile

This enabled to specify Version qualifier which will result in a package in following format
`fleet-server-{VERSION}-{VERSION_QUALIFIER}-{IS_SNAPSHOT}-darwin-x86_64.tar.gz `
e.g
`fleet-server-8.0.0-alpha1-SNAPSHOT-darwin-x86_64.tar.gz `
when variable is not present name follows notation as before
test by running `SNAPSHOT=true PLATFORMS=darwin/amd64 VERSION_QUALIFIER=alpha1 make release`
Conforming with release process and to be on par with other products.

Accept version qualifier

---

cmd/fleet/handleCheckin.go
cmd/fleet/schema.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Allows to specify the timeout on the the individual actions in seconds.
This will be applied when the agent calls PerformAction
https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_application.go#L57
if the timeout is specified. Otherwise it will use the default 1 minute timeout. 
This should allow the actions such as containment to set the individual timeout if they expect the action to take longer than one minute.
- Relates https://github.com/elastic/kibana/issues/105477
An example of the action POST with 30 secs timeout:

Add action timeout

---

cmd/fleet/userAgent.go
cmd/fleet/userAgent_test.go
internal/pkg/ver/check.go
internal/pkg/ver/check_test.go

This updates the user-agent version checking to remove anything after the version `-` and ignores it.
`8.0.0-alpha1` is a testing release of the stack and this causes issue with the version constraint checks in Fleet Server.
- Closes #608

Improve version checking for 8.0.0-alpha1

---

cmd/fleet/handleCheckin.go
cmd/fleet/handleEnroll.go
cmd/fleet/userAgent.go
cmd/fleet/userAgent_test.go
internal/pkg/checkin/bulk.go
internal/pkg/checkin/bulk_test.go
internal/pkg/dl/constants.go

Populate agent.id field in .fleet-agents index as requested here:
https://github.com/elastic/fleet-server/issues/595
@scunningham The current agent schema/mapping has "version" field along with "id", if we populate only the "agent.id" it will save the version as "" empty string, so I updated the code to capture the "agent.version" too. Also assumed that the version could be updated for the same "agent.id".
Could you check if my assumptions are correct there? Thanks!
- Closes https://github.com/elastic/fleet-server/issues/595

Populate agent.id field in .fleet-agents index

---

internal/pkg/monitor/monitor.go
internal/pkg/monitor/monitor_test.go

Adds index refresh call after fetch if the list of hits/results has holes.
After discussion with Elasticsearch team it looks like the current global checkpoints
API doesn't not gurantee the list of document without holes on
subsequent index search and there is still a slim chance of this with
our current implementation. Elastisearch team is working on getting the
refresh implemented on thier side, and for now recommended to do the
refresh before fetch if there are holes detected in the result.
Added the check for the holes and refetch, here are the steps:
1. Call Global checkpoints = 5
2. Search = 1, 2, 3, 5.
3. Manual refresh
4. Search and get 4,5
5. Return to step 1
Covers the edge case where the fetched documents lists after checkpoint API could still potentially have holes.
In …

Add index refresh call after fetch if the list of hits has holes

---

cmd/fleet/handleCheckin.go

When running on previous version of Fleet Server the version of the Elastic Agent was not stored. With 7.15 the version was added, but that means that on check-in it needs to handle the case that the metadata is not present.
This adds a check to ensure that the metadata is present before checking the version field. If not present then the version will be updated correctly in 7.15 as it should.
- ~~[ ] I have added tests …

Fix panic caused by Agent check-in when Fleet Server is upgraded from 7.14.0 previous

---

cmd/fleet/handleCheckin.go
internal/pkg/model/ext.go
internal/pkg/model/ext_test.go

Addresses comment on previous PR:
https://github.com/elastic/fleet-server/pull/683#issuecomment-909984620
* Extract the get agent new version into a function
* Add full unit test coverage for that part
- Relates https://github.com/elastic/fleet-server/pull/683#issuecomment-909984620

Encapsulate the agent new version safe check, full unit test coverage

---

.gitignore
Makefile
NOTICE.txt
cmd/fleet/main.go
cmd/fleet/metrics.go
cmd/fleet/server_integration_test.go
go.mod
go.sum
internal/pkg/build/build.go
internal/pkg/es/client.go
main.go

* Set User-Agent in HTTP requests that looks like the following:
```
User-Agent: Elastic-Fleet-Server/8.0.0 (darwin; amd64; b1fef53; 2021-08-23 18:50:14 +0000 UTC)
```
* Update elasticsearch client on the 7.x branch commit that implemented the addition of the User-Agent https://github.com/elastic/go-elasticsearch/commit/845c8efe54a7a8fd0f43cf6f9b33e53371d2c237
* Add built time for consistency with the libbeat user agent
Not sure how important this is, but it addresses https://github.com/elastic/fleet-server/issues/636
Leaving up to the Fleet/Agent team to decide if this is needed or not.
- Closes https://github.com/elastic/fleet-server/issues/636
Wireshark capture

Set User-Agent in HTTP requests

---

cmd/fleet/main.go
cmd/fleet/main_integration_test.go
internal/pkg/cache/cache.go
internal/pkg/cache/impl.go
internal/pkg/cache/impl_integration.go
internal/pkg/cache/impl_ristretto.go
internal/pkg/dl/enrollment_api_key.go
internal/pkg/testing/esutil/index.go
internal/pkg/testing/suite/suite.go

There are 3 problems that this PR solves:
1. Configurations changes to the `fleet.*` or the `output.*` sections of the Fleet configurations would not cause the Fleet Server to restart the required sections of the server for those changes to actually take affect.
2. In the case that the configuration change fails (maybe a transient elasticsearch connection problem) then the Fleet Server would roll all the way back to its initial configuration sent from Elastic Agent.
3. No integration tests existed for Fleet Server being controlled by Elastic Agent.
This solves each problem as follows:
1. It adjusts the configuration change checking code to check for the `fleet.*` and `output.*` sections.
2. It always stores the last given configuration in the FleetServet struct so on restart it always …

Fix issues with config reloading

---

cmd/fleet/handleCheckin.go
internal/pkg/dl/actions.go
internal/pkg/es/holes.go
internal/pkg/es/holes_test.go
internal/pkg/es/refresh.go
internal/pkg/monitor/monitor.go

This covers one more edge case for actions in multiple replica shards environment per discussion with Elasticsearch team
The edge use case:
1. the monitor fetches from one replica shard
2. result has no holes
3. the index refresh is skipped if there is no holes
4. the seqno is advanced forward as expected
5. the agent upon check-in, by the random draw of luck fetches actions from different replica shard that doesn't have all the documents indexed in that range
6. the result can have holes
In order to cover this use case need to add the holes detection and refresh upon the agent initial actions fetch during checkin.
* Extracted HasHoles function into es package so it can be reused in two places: the monitor and the checking handler
* Extracted es.Refresh function so it can be reused in two …

Add "hole" detection and refresh for the agent actions fetch upon initial check in

---

.mergify.yml

1. Tidy up old branches.
2. Notify PR contributors about the backport policy.
This policy will notify what are the different backport options and tag the PR with the `backport-skip`.
See https://github.com/elastic/apm-pipeline-library/pull/1281#issuecomment-922766344 and https://github.com/elastic/apm-pipeline-library/pull/1281#event-5327050151

[mergify] notify if no backport labels on the PRs targeting the master branch

---

cmd/fleet/handleAck.go
cmd/fleet/handleArtifacts.go
cmd/fleet/handleCheckin.go

Backport: Proper mapping for agentId field.
The field "id" does not map.  Use a field name that maps.

Change agentId field to a value that elastic will map.

---

cmd/fleet/handleAck.go
cmd/fleet/schema.go
internal/pkg/es/mapping.go
internal/pkg/model/schema.go
model/schema.json

Add ```action_response``` to the ```.fleet-actions-results```. 
This allows to store a small payload from the beat/app action response if needed.
Currently this feature is needed for endpoint and could be useful for osquerybeat actions.
The endpoint team is hoping to get this into 7.16 if possible.
- Relates: https://github.com/elastic/security-team/issues/1924
Confirmed mapping is created:
Confirmed the data is indexed and searchable with osquerybeat that now provides the number of rows returned by the query:

Add action_response field into .fleet-actions-results

---

cmd/fleet/main.go
internal/pkg/checkin/bulk.go
internal/pkg/dl/constants.go
internal/pkg/dl/migration.go

Fix missing agent record migration added in 7.15.
At boot, query for agent records that do not contain agent.id field and fix them up.  Should be a fast noop when no changes necessary.
In addition, fixes issue where agent.version was being written at root instead of as a child of the agent object.
Upgrade from 7.14, or enroll with 7.15 or later, and delete the "agent" object from the agent record in .fleet-agents.  This has been tested at scale, supports retry version conflict.  Once migration has occurred, typical response time from Elastic is less then 10ms (not including TLS roundtrip).
- Closes https://github.com/elastic/fleet-server/issues/819

[7.16] Migrate agent.id field from 7.14 to 7.15+

---

cmd/fleet/auth.go
cmd/fleet/main.go
internal/pkg/checkin/bulk.go
internal/pkg/dl/constants.go
internal/pkg/dl/migration.go

Fix missing agent record migration added in 7.15.
At boot, query for agent records that do not contain agent.id field and fix them up.  Should be a fast noop when no changes necessary.
In addition, fixes issue where agent.version was being written at root instead of as a child of the agent object.
Upgrade from 7.14, or enroll with 7.15 or later, and delete the "agent" object from the agent record in .fleet-agents.  This has been tested at scale, supports retry version conflict.  Once migration has occurred, typical response time from Elastic is less then 10ms (not including TLS roundtrip).
- Closes https://github.com/elastic/fleet-server/issues/819

Migrate agent.id field from 7.14 to 7.15+

---

.mergify.yml

Use the `backport-` labels approach similar to Beats, e2e-testing
Same user experience
Or we can apply the existing `Fleet-Server` backport labels in Beats and e2e-testing

[mergify] use backport- labels

---

cmd/fleet/main.go
cmd/fleet/userAgent_test.go
internal/pkg/config/config_test.go
internal/pkg/config/gc.go
internal/pkg/config/input.go
internal/pkg/dl/actions.go
internal/pkg/dsl/size.go
internal/pkg/es/error.go
internal/pkg/gc/actions.go
internal/pkg/gc/actions_integration_test.go
internal/pkg/gc/schedules.go
internal/pkg/scheduler/scheduler.go
internal/pkg/scheduler/scheduler_test.go
internal/pkg/testing/actions.go
internal/pkg/wait/wait.go

Due to current limitations of the index changes monitoring with utilizing Elasticsearch document sequence numbers for fleet actions, the .fleet-actions index can't be rolled over or have multiple shards.
Until this problem is solved on Elasticsearch side we have to continue using the same single index/shard, that allows the implementation to rely on the guaranteed incremental document sequence number. In order to reduce the number of documents stored in the index over time we need to introduce some kind of cleanup procedure for removal of the old documents.
This PR introduces scheduled cleanup for the expired fleet actions.
The current default is to remove the expired document where the expiration date/time is older than 30 day from the moment the cleanup job runs. The cleanup runs first …

Periodic expired actions cleanup

---

internal/pkg/dl/actions.go

Fixes the crash on expired actions search if the .fleet-actions index doesn't exists (on a clean install) on master and 8.0 branches.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47d5a7c]
goroutine 60 [running]:
github.com/elastic/fleet-server/v7/internal/pkg/dl.FindExpiredActionsHitsForIndex({0x4dde6d8, 0xc0001d2400}, {0x4c91d88, 0xe}, {0x4dfc250, 0xc00013ed00}, {0x1f4, 0xc000032fd0, 0x567b960}, 0x3e8)
/Users/amaus/elastic/fleet-server/internal/pkg/dl/actions.go:131 +0x27c
github.com/elastic/fleet-server/v7/internal/pkg/gc.cleanupActions({0x4dde6d8, 0xc0001d2400}, {0x4c91d88, 0xe}, {0x4dfc250, 0xc00013ed00}, {0xc000735bb0, 0x1, 0xc000394000}) …
```

Fix: Fleet Server crashes on expired actions search

---

internal/pkg/gc/actions_integration_test.go

Adds integration test coverage for the case where the index is not found.
This is related to the defect that was not covered by the integration test:
https://github.com/elastic/fleet-server/pull/876
Add integration test coverage for actions cleanup with non-existing index
```
make test-int 
```
or if the instance of Elasticsearch is already running:
```
make test-int-set
```
- Relates https://github.com/elastic/fleet-server/pull/876

Add integration test coverage for actions cleanup with non-existing index

---

NOTICE.txt
go.mod
go.sum

Updated to 7.15.1 tag that includes "Allow to overwrite User-Agent http request header" 
https://github.com/elastic/go-elasticsearch/commit/eeed8d4c1c5393ff4ae61deb809edf5b1e1c9af8
Previously we had to use commit hash to pick up this change.
Updates go-elasticsearch dependency

Update go-elasticsearch to the latest 7.15.1 version

---

cmd/fleet/handleEnroll.go
cmd/fleet/main.go
cmd/fleet/router.go
cmd/fleet/server_test.go
internal/pkg/rollback/rollback.go

The cleanup code for enrollment errors is scattered in couple of places:
```
Router.handleEnroll->
->EnrollerT.handleEnroll
->EnrollerT.processRequest
->EnrollerT._enroll
->generateAccessApiKey + createFleetAgent(If Fail)->invalidateApiKey
->writeResponse(If Fail) 
-> wipeGhosts
-> delete Agent document
-> invalidateApiKey
```
This change consolidates the cleanup code through the rollback/cleanup wrapper. 
Implemented a simple "rollback" wrapper that can have the "rollback/cleanup" cleanup functions added as needed. The ```Rollback``` is called on error which in turn calls the registered cleanup functions.
For example, the log when Fleet Server fails to create the agent record:
```
{"log.level":"error","service.name":"fleet-server","http.request.id":"01FMQW2DC9GXDDX3Z8S6YCTZ0M","mod":"enro …
```

Improve the cleanup code on enrollment handling error

---

cmd/fleet/main.go
internal/pkg/config/gc.go
internal/pkg/dl/actions.go
internal/pkg/es/result.go
internal/pkg/gc/actions.go
internal/pkg/gc/actions_integration_test.go
internal/pkg/gc/actions_test.go
internal/pkg/gc/schedules.go

Improve expired actions cleanup, use _delete_by_query instead.
The original implementation was selecting action ids and deleted them by document id, although batched, it was suboptimal.
Replaces current cleanup implementation with ```_delete_by_query```

Improve expired actions cleanup, use _delete_by_query instead

---

.mergify.yml

Migrate from the `merge action` to the `queue action`.
See https://docs.mergify.io/actions/queue/#queue-rules to know more about how the `queue` command works.
We use the merge action to automerge automated PRs, so we cannot use this approach from January 2022
```
The configuration uses the deprecated strict mode of the merge action.
A brownout is planned for the whole December 6th, 2021 day.
This option will be removed on January 10th, 2022.
For more information: https://blog.mergify.io/strict-mode-deprecation/
```

Mergify: replace merge action for the queue action

---

cmd/fleet/main.go
internal/pkg/config/instrumentation.go

Adds TLS configuration options for the APM instrumentation, using env
vars to configure the APM HTTP Tracer since it currently doesn't support
setting those values in Golang. We'll follow up on this once the apm
tracer has a function to create a new tracer with configurable settings
via config struct.
Adds a TLS config struct and sets the relevant values as env vars for the APM tracer to configure itself.
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~
Follow up from #898

instrumentation: Add "tls" configuration options

---

cmd/fleet/server.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go

What this PR solves is a problem when agent got unenrolled on heavier load when agent managing fleet server cannot checkin to it's own server so it will fallback to unenroll.
Closes https://github.com/elastic/fleet-server/issues/741 
Problem is solved by adding internal endpoint which is used for communication on local network (with agent handling fleet server)
It lets FS to spin up 2 set of handlers, one on public 8220 and one on port defined in config. 
This needs to be tested with work on `elastic-agent` Link: https://github.com/elastic/beats/pull/28993
- Start stack
- Install agent with FS in a policy
- Check ports
```
sh-3.2# lsof -i -P | grep LISTEN | grep fleet
fleet-ser  7056            root   19u  IPv4 0xba7881a9227099a5      0t0    TCP localhost:{random_port} (LISTEN)
fleet-ser …
```

[7.16] Support multiple endpoints

---

cmd/fleet/server.go
internal/pkg/config/config_test.go
internal/pkg/config/input.go

What this PR solves is a problem when agent got unenrolled on heavier load when agent managing fleet server cannot checkin to it's own server so it will fallback to unenroll.
Closes https://github.com/elastic/fleet-server/issues/741 
Problem is solved by adding internal endpoint which is used for communication on local network (with agent handling fleet server)
It lets FS to spin up 2 set of handlers, one on public 8220 and one on port defined in config. 
This needs to be tested with work on `elastic-agent` Link: https://github.com/elastic/beats/pull/28993
- Start stack
- Install agent with FS in a policy
- Check ports
```
sh-3.2# lsof -i -P | grep LISTEN | grep fleet
fleet-ser  7056            root   19u  IPv4 0xba7881a9227099a5      0t0    TCP localhost:{random_port} (LISTEN)
fleet-ser …
```

[8.0] Support multiple endpoints

---

cmd/fleet/main.go
internal/pkg/es/client.go

Add deprecation logs when username/password is used to connect to Elasticsearch.
Closes #977

Deprecate username/password when connecting to es

---

cmd/fleet/main.go
internal/pkg/es/client.go

[7.16] (backport #995) Deprecate username/password when connecting to es

---

cmd/fleet/error.go
internal/pkg/coordinator/monitor.go

This PR adds a log line signifying the recovery of fleet server while polling ES. Also, 
For the logging change:
Keeps track of the errored state of the monitor, and on the first successful communication with poll it logs at info level.
For surfacing the error through the http router:
Returns a `503` in the case where the request to ES results in an error containing `connection refused`. This method of error classification was copied from [here](https://github.com/golang/go/blob/master/src/net/dial_test.go#L810), as I was unable to hunt down an error instance to compare the error against.
`make local` then run the binary against a local ES instance. Kill the ES instance.
To test the logging change:
Wait til the logs show the fleet server is having difficulties communicating with ES, then …

added more detailed logs around ES communication failure

---

.mergify.yml

PRs that were created by the automation then close them if they are obsoleted.
They are obsoleted if they have a conflict.
- Relates https://github.com/elastic/beats/pull/29455

mergify: close automated prs if they are obsoleted

---

NOTICE.txt

Update Copyright year, otherwise the builds will fail since the linting verifies this

chore: update year 2022

---

NOTICE.txt

(cherry picked from commit 469ae42699984df7f1823c32c79aae854f4eafea)
We also need #1067 in 7.16 due to 7.16.3

chore: update year 2022 (#1067)

---

cmd/fleet/schema.go
internal/pkg/apikey/apikey_integration_test.go

This PR fixes issue spotted in: https://github.com/elastic/elastic-package/pull/650
```
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","http.request.id":"01FSMA8YRG2G2DDJESQ6ZCVW42","mod":"enroll","fleet.enroll.apikey.id":"wm2kaH4BMg40PYJ8YCOR","error.message":"fail CreateAPIKey: [400 Bad Request] {\"error\":{\"root_cause\":[{\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: An application name prefix must match the pattern ^[a-z][A-Za-z0-9]*$ (found '.fleet');\"}],\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: An application name prefix must match the pattern ^[a-z][A-Za-z0-9]*$ (found '.fleet');\"},\"status\":400}","http.response.status_code":400,"event.duration":306104815,"@timestamp":"2022-0 …
```

Fix application name in API key

---

internal/pkg/logger/http.go

Instead of writing `HTTP Done` on every request successful or not we
will only log when request codes are non 2xx.
Closes #1083
Reduce the cognitive load of dealing with a "HTTP Done log" statement, they were recorded on every request.

Remove `HTTP Done` from the log on every request.

---

cmd/fleet/handleStatus.go
cmd/fleet/handleStatus_test.go
cmd/fleet/main.go
cmd/fleet/router.go
cmd/fleet/schema.go
cmd/fleet/server_test.go
dev-tools/buildlimits/buildlimits.go
internal/pkg/config/env_defaults.go
internal/pkg/config/limits.go

Adds additional build info to the status API response,
addresses issue https://github.com/elastic/fleet-server/issues/1108
Adds additional build info to the status API response.
- Closes https://github.com/elastic/fleet-server/issues/1108

Extend the existing status API with build info

---

.github/CODEOWNERS

Add @elastic/elastic-agent-control-plane to the CODEOWNERS to get
notified on new pull request.
Allow the Elastic Agent control plane team to get notified on new pull request.

Add @elastic/elastic-agent-control-plane to the CODEOWNERS file

---

.mergify.yml
main.go

Update the master branch to 8.2.0

Update master branch to 8.2.0

---

.github/workflows/qa-labels.yml

This mirrors the automation we've added to the beats repo in https://github.com/elastic/beats/pull/30303:
Whenever a PR is merged with the Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, or Team:Elastic-Agent-Control-Plane labels and the PR closes an issue(s):
Copy the vX.X.X labels to the closed issue(s)
Add the QA:Ready for Testing label to the closed issue(s)

Add github action for automating QA labels

---

.ci/Jenkinsfile

Notify build status as GitHub checks for each major stage in the CI
Trying to improve the development experience while contributing to this repository.

ci: notify stages in the CI with GitHub checks

---

cmd/fleet/handleAck.go
cmd/fleet/handleAck_test.go
cmd/fleet/schema.go
internal/pkg/model/schema.go
model/schema.json

Populates input_type for the .fleet-actions-results. This allows to use kibana transformations on .fleet-actions-results for specific integration without a need to correlate them to the original .fleet-actions (via the action_id)
Copies ```input_type``` from the fleet action to the fleet action response document.
- Requires https://github.com/elastic/beats/pull/30562

Populate action_input_type for the .fleet-actions-results

---

.ci/Jenkinsfile

Use the flat directory as that's the folder structure used in some other projects
To help the e2e-testing to work with the defined folder structure
https://github.com/elastic/fleet-server/pull/1147 was the initial PR that enabled this.
```
gsutil list -l gs://beats-ci-artifacts/fleet-server/commits/455a032873113a8d35309c131ca3d2afaae850b1
Updates are available for some Cloud SDK components.  To install them,
please run:
$ gcloud components update
7343542  2022-03-17T13:23:05Z  gs://beats-ci-artifacts/fleet-server/commits/455a032873113a8d35309c131ca3d2afaae850b1/fleet-server-8.2.0-darwin-arm64.tar.gz
169  2022-03-17T13:23:04Z  gs://beats-ci-artifacts/fleet-server/commits/455a032873113a8d35309c131ca3d2afaae850b1/fleet-server-8.2.0-darwin-arm64.tar.gz.sha512
7846357  2022-03-17T13:23:05Z …
```

ci: store build/distributions

---

.ci/scripts/test-release.sh
CHANGELOG.next.asciidoc
Makefile

This use the `darwin-aarch64` suffix instead of `darwin-arm64`, this
align the naming with the other products of the stack.
```
❯ make  release-manager-snapshot                                                                                                                                       [15:36:20]
./dev-tools/run_with_go_ver /Library/Developer/CommandLineTools/usr/bin/make release
v0.3.2
GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s -X main.Version=8.2.0-SNAPSHOT -X main.Commit=b8a6346 -X main.BuildTime=2022-03-28T19:36:21Z" -buildmode=pie -o …
```

Use darwin-aarch64 artifact when building darwin

---

.github/workflows/golangci-lint.yml

This run linter per operating system if we ever had specific OS code
defined with different golang build tags.
This also use the `--whole-files` arguments since from our testing
using only the patch strategy was making the linting unreliable.
See https://github.com/elastic/elastic-agent-libs/pull/30 for tests.

Align golangci-lint with elastic-agent/beats

---

.ci/packaging.groovy
.ci/scripts/release-manager.sh
Makefile

Enable the Daily Release Artifacts for the Fleet Server project (Snapshots only)
If something bad happens then it sends an email/slack to:
- `#fleet-server`
- `fleet-server+package@...`
A specific pipeline in charge of publishing the snapshots on a merge-commit only
Requires https://github.com/elastic/fleet-server/pull/1233
Requires https://github.com/elastic/apm-pipeline-library/pull/1618
https://artifacts-snapshot.elastic.co/fleet-server/8.2.0-6e3e8531/summary-8.2.0-SNAPSHOT.html has been generated (see [build](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Ffleet-server-package-mbp/detail/PR-1234/46/pipeline/262))
Support BCs (to be done later on)

ci: packaging pipeline for the snapshots

---

.mergify.yml

Automated backports to 8.1 and 8.2 did not work because of Mergify's config was outdated.
It uses `main` as base branch for Mergify to resolve the rules for those two branches

fix: update mergify's base branch for 8.1 and 8.2

---

.github/workflows/golangci-lint.yml

We have seems weirds behavior in Darwin and Windows execution of the
linting. Until all the errors are fixes this is a bit counter productive
to run it on everything. It will just multiply the errors detected.
Ref: https://github.com/elastic/fleet-server/pull/1270

Remove windows and darwin linting

---

.ci/packaging.groovy

This is the very last part for the DRA related to the `staging` workflow
- Run in parallel the `staging` and `snapshot` package generation.
- Enable `staging` for the release branches.
- Enable `snapshot` for the release and main branches.
See [job](https://beats-ci.elastic.co/job/Ingest-manager/job/fleet-server-package-mbp/job/PR-1280/)
This [build](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Ffleet-server-package-mbp/detail/PR-1280/9/pipeline/452)
created:
- [staging](https://artifacts-staging.elastic.co/fleet-server/8.3.0-894cf6bf/summary-8.3.0.html)
- [snapshot](https://artifacts-snapshot.elastic.co/fleet-server/8.3.0-0c0699c2/summary-8.3.0-SNAPSHOT.html)

ci: daily release artifacts for staging

---

cmd/fleet/handleCheckin.go
internal/pkg/policy/policy_output.go
internal/pkg/policy/policy_output_test.go

This fixes a few issues:
- When the hash on the permission and the hash on the agent were the
same the key was not added to the output. This was causing the agent to
not be able to connect to Elasticsearch. If you change an integration
policy field, as the `host` field,  and the data stream are the same the permission hash will
stay the same.
- Fix a possible issue when the new key was not saved on the Agent model, the
the key was only saved when we were targetting a default agent policy.
Currently, we only support a single ES output so this should always be saved.
- Reorganize the test to ensure that all the scenarios from the `case switch` are tested
- Wait for the Agent's status to be Healthy
- Change a integration field value.
~~- [ ] I have made corresponding changes to the …

Always add `api_key` to Elasticsearch output

---

.golangci.yml
cmd/fleet/main.go
cmd/fleet/server_integration_test.go
internal/pkg/api/auth.go
internal/pkg/api/error.go
internal/pkg/api/handleAck.go
internal/pkg/api/handleAck_test.go
internal/pkg/api/handleArtifacts.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleChecking_test.go
internal/pkg/api/handleEnroll.go
internal/pkg/api/handleStatus.go
internal/pkg/api/handleStatus_test.go
internal/pkg/api/metrics.go
internal/pkg/api/router.go
internal/pkg/api/schema.go
internal/pkg/api/server.go
internal/pkg/api/server_integration_test.go
internal/pkg/api/server_test.go
internal/pkg/api/userAgent.go
internal/pkg/api/userAgent_test.go
internal/pkg/build/build.go

Start refactoring cmd so api server code is in internal/pkg/api.
This makes it a bit clearer where to find API related code when developing the fleet-server.

Refactor: move files from cmd/fleet to pkg/api

---

.github/workflows/golangci-lint.yml

Bump golangci version to v1.45.2 to support properly Apple M1.

Update Golangci-lint to 1.45.2

---

.mergify.yml

Since we shipped 8.0, by default not backports are needed anymore. Because of this the default request to add a backport label is removed.

Remove backport-skip automation

---

.ci/Jenkinsfile
.ci/packaging.groovy

Use the downstream pattern to run the packaging pipeline and then pass over the Git commit to be used.
The parentstream pattern does not support the Git commit approach by default and therefore it requires further changes to accomplish the same.
In the CI.
When the `packaging` pipeline runs there is a chance that a new commit has been pushed to the `main` branch before the `packaging` has even get triggered, therefore the `packaging` pipeline will run but it will not use the original commit.
While using the downtream pattern, then we can orchestrate what builds to run from the `main pipeline` and the pass the sha commit to those jobs. 
Similar to https://github.com/elastic/apm-server/pull/7982

ci: use downstream pattern

---

.ci/jobs/fleet-server-package-mbp.yml

use the downstream pattern as stated in https://github.com/elastic/fleet-server/pull/1439

jjbb: suppress-scm-triggering

---

.ci/Jenkinsfile

Cosmetic change so the post-builds step do only reporting.

ci: use post-builds for reporting only

---

.ci/Jenkinsfile

Create a GitHub issue:
* As soon as a build is failing an issue should be created
* It should be assigned to Elastic Agent Data Plane team (it relies on the GitHub labels to do so)
Use GitHub to drive the on-call process when the CI fails
Similar to https://github.com/elastic/beats/pull/31954

ci: enable build notifications as GitHub issues

---

.ci/Jenkinsfile

Enable `test-flakiness` detection
Track `test-flakiness` help to monitor how often a particular test failure happens and has been categorised as flaky.
This is similar done for Beats -> https://github.com/elastic/beats/issues?q=is%3Aissue+is%3Aopen+label%3Aflaky-test

ci: enable flaky test detector

---

CHANGELOG.next.asciidoc
internal/pkg/coordinator/monitor.go
internal/pkg/coordinator/monitor_integration_test.go

When Fleet Server is offline for a period bigger or equal to the
unenrollTimeout, on reboot the Server will start to automatically
unenroll Elastic Agent without giving them a chance to communicate with
the system. Instead on reboot we will give a grace period equivalent to
the unenrollTimeout this will give enough time to the Elastic Agent to
communicate back to Fleet Server and update their last checkin time.
Fixes: #1500

On Fleet Server reboot gives a grace period

---

.ci/Jenkinsfile
.ci/jobs/fleet-server-package-mbp.yml

Otherwise it won't be available for tags and will report failures since the packaging does not discover tags
There is no need, to run on tags since the tags are coming from the official releases, so we can save build time

ci: run packaging by default on branches only

---

CHANGELOG.next.asciidoc
internal/pkg/bulk/bulk_test.go
internal/pkg/coordinator/monitor.go
internal/pkg/coordinator/monitor_integration_test.go

There were a race condition possible with between the enrolling goroutine and the main coordinator routine. I've added a mutex to protect the access of the `policiesCanceller` and audited the remaining part of the code. Everything else are executed in the same goroutine (via channel's select) so the `policies` field is unaffected. But, I think the code would benefit to be `cleanup` and the _policies_ and the _policiesCanceller_  field to be consolidated in a single field AND moving the manipulation the values either using channel or via methods on the struct. I've initially looked to refactor the code, but I would clearly have taking more time. Looking a the panic described in #1738 the critical field field would be the _policiesCanceller_.
~~- [ ] I have commented my code, particularly …

Protect access to policiesCanceller using a mutext

---

.ci/Jenkinsfile

Caused by the migration to fleet-ci
https://fleet-ci.elastic.co/job/fleet-server/job/fleet-server-package-mbp/
Caused by https://github.com/elastic/fleet-server/pull/1199

Fix path to the packaging

---

.ci/packaging.groovy

Change stage name to reflect `DRA staging` is not available for `main`
DRA staging does not run for the `main` branch but the `release branches` (7.17, 8.4...)
I manually triggered the [build](https://fleet-ci.elastic.co/blue/organizations/jenkins/fleet-server%2Ffleet-server-package-mbp/detail/PR-1840/3/pipeline/) for this PR, so the change is just the stage name.

ci: rename dra staging for release dra release staging 

---

CHANGELOG.next.asciidoc
internal/pkg/api/auth.go

This allows us to run a scale test with debug logging enabled (trace is not supported right now) and measure how long API key auth is taking, including cache hit rate.
Updates the logging code
Enable debug logging, see the `ApiKey authenticated` logs.
Closes #1125

Make authc log debug and add cache hit field

---

CHANGELOG.next.asciidoc

Go 1.18 breaks compatibility with SHA-1 signed certificates. Document this in the agent changelog. This is the same text we used for beats with the PR number updated.

Add Go 1.18 upgrade to breaking changes section

---

version/version.go

The 8.5.0 branch is created, bump the version on main to 8.6.0.
@v1v I think we can automate this for fleet server like we have for Beats (see https://github.com/elastic/beats/pull/33154).

Bump version to 8.6.0

---

CHANGELOG.next.asciidoc
internal/pkg/api/handleAck.go
internal/pkg/bulk/opBulk.go
internal/pkg/coordinator/monitor.go
internal/pkg/dl/servers.go
internal/pkg/policy/policy_output.go

It solves an issue where calling an action through the bulker would result in errors on a single document being ignored. It also adds `bulk.WithRetryOnConflict(3)` in many places that update the `.fleet-agents` index. Being that the `.fleet-agents` index is written to often it is possible that conflicts will occur and elasticsearch should retry on conflicts.
This changes the `waitBulkAction` to look at the status code and error document of a bulk action response to ensure that an error should not be returned instead of the document.
Scale test runs are the only place to really test that this solves the issue.
- ~~[ ] I have added tests that prove …

Catch error in waitBulkAction. Add bulk.WithRetryOnConflict(3) in multiple places.

---

CHANGELOG.next.asciidoc
internal/pkg/api/auth.go

As I was going about updating the fields that get mapped in our logs on Cloud, I noticed that the name of this recent log property that I added in https://github.com/elastic/fleet-server/pull/1870 does not match the `fleet.apikey.id` property we use elsewhere. Updated this to fix.
Changes the field name to match

Update apikey.cache_hit log field name to match convention

---

CHANGELOG.next.asciidoc
internal/pkg/config/cache.go
internal/pkg/config/config_test.go
internal/pkg/config/limits.go

Custom user specified values for cache and server limits are silently discarded when `LoadLimits` is ran.
Fleet-server will use any specified cache or server limit values over whatever is returned by the default/agent number loader. For example, if A max body size is specifically set to a value such as 5MB, and the default returned by the LoadLimits is 1MB, the 5MB value is used.
- Closes #1841

LoadLimits does not override existing values

---

CHANGELOG.next.asciidoc
internal/pkg/api/handleCheckin.go
internal/pkg/api/schema.go
internal/pkg/checkin/bulk.go
internal/pkg/checkin/bulk_test.go
internal/pkg/dl/constants.go
internal/pkg/model/schema.go
model/schema.json

Help troubleshooting by storing status message in Agent doc.
On checkin, taking the `Message` field from the request, and storing it in `last_checkin_message` of the agent document.
- Required for https://github.com/elastic/elastic-agent/issues/1151

Storing checkin message in last_checkin_message

---

cmd/fleet/main.go
internal/pkg/dl/migration.go

The forward port of https://github.com/elastic/fleet-server/pull/1921, the https://github.com/elastic/fleet-server/pull/1926 PR, includes a few improvements on the log messages, this PR backports those improvements.
By backporting the extra changes on the forwardport https://github.com/elastic/fleet-server/pull/1926

Improve migration logs on 8.5 branch

---

internal/pkg/dl/migration.go
internal/pkg/dl/migration_integration_test.go

There's an issue with large number of agent and ongoing migration. Migration is stuck in a loop and queries also documents which were already updated. 
Issue: https://github.com/elastic/fleet-server/issues/1958
Query was looking for agent based on missing fields from newly introduced set.
This PR changed the approach around and returns agent with deprecated fields present. These fields are removed by a script so in other run they're not returned
https://github.com/elastic/fleet-server/issues/1958

Updated migration query to match items with deprecated field present

---

.github/workflows/golangci-lint.yml

Use the `setup-go` action with the `go-version-file` input so it reads the file `.go-version`
Avoid the logic to read and create env variables and use the undocumented `.go-version-file` 
See https://github.com/actions/setup-go/pull/295

actions: use go-version-file: .go-version

---

NOTICE.txt
go.mod
go.sum

backport broke cloud reporting, updating elastic-agent-client version again to a version based on tag. 
https://github.com/elastic/fleet-server/pull/2149
https://github.com/elastic/fleet-server/pull/2149
cc @michel-laterman

Update client dependency to latest 7.0.2"

---

NOTICE.txt
dev-tools/buildlimits/buildlimits.go
go.mod
internal/pkg/api/error.go
internal/pkg/api/handleAck.go
internal/pkg/api/handleArtifacts.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleEnroll.go
internal/pkg/api/metrics.go
internal/pkg/apikey/apikey.go
internal/pkg/config/env_defaults.go
internal/pkg/dl/migration.go

Go has error wrapping as part. of the stdlib since v1.13.0.
This PR removes an external library that was used in the repo to provide the same functions.
The library is still an indirect requirement as other imports use it.

Remove direct pkg/errors dependency

---

Dockerfile.build
Makefile

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* This PR solves CI build issues.
* Ref: https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/fleet-server/pipelines/fleet-server-mbp/pipelines/PR-2180/runs/4/steps/290/log/?start=0
* Create a cache directory within the docker image at `/.cache`
* Forward local uid and gid when we run the docker image.
* Run the following make target `make docker-release`.

Correct build using docker image

---

version/version.go

Updates references to the new release 8.6.1.
Merge after the release 8.6.0.

[Release] Update version to 8.6.1

---

CHANGELOG.next.asciidoc
internal/pkg/config/config_test.go
internal/pkg/config/fleet.go

The log level provided by the Agent is "warn", and crashes the fleet-server as it expects "warning".
Config will parse "warning" and "warn" as `zerolog.WarnLevel`
- Closes #2328

Allow the the Warn log level to be specified as "warning" and "warn"

---

.github/workflows/bump-elastic-stack-snapshot.yml
.github/workflows/bump-golang.yml

Use GitHub composite action
Reuse code and solve the existing issue with Workflows won't be enabled for PRs created on behalf of `GitHub actions [bot]`, see https://github.com/elastic/ecs-logging-java/pull/200
Similar to https://github.com/elastic/ecs-logging-java/pull/201
Requires https://github.com/elastic/apm-pipeline-library/pull/2076

action: use composite updatecli

---

internal/pkg/api/handleEnroll.go
internal/pkg/api/handleEnroll_test.go

When an Elastic Agent is enrolled with the same tag multiple tags, they are treated as separate tags.
Issue: https://github.com/elastic/fleet-server/issues/1596
This PR adds a helper method to remove duplicate tags during Elastic Agent enrollment.
1. Run fleet-server locally with these changes.
2. Enroll a new Elastic Agent with duplicate tags. For instance, if running elastic-agent locally using Docker, pass the flag `-e ELASTIC_AGENT_TAGS=foo,foo,foo,foo`.
3. The duplicated tag should only appear once in the new Agent.
- Closes [#123](https://github.com/elastic/fleet-server/issues/1596)

Remove agent tag duplicates

---

.mergify.yml

Remove closed branches created by the automation
Remove backports to old 8.x branches but 8.6 and 8.7
Delete updatecli branches when PRs were merged/closed

mergify: delete branches created by the updatecli, update backports

---

internal/pkg/config/config.go
internal/pkg/config/config_test.go

added a really simple unit test and comments to explicitly state how fleet-server handles env vars

Add comments and unit test for gathering variables from env var

---

internal/pkg/policy/standalone.go
internal/pkg/policy/standalone_test.go

Resolve #2421 
Mark Fleet server as healthy in standalone even if the `.fleet-policies` index is not yet created.
I updated the unit test.
I manually tested this like this:
1. With a fresh ES and Kibana
2. Create a service token
```
curl -X POST http://localhost:9200/_security/service/elastic/fleet-server/credential/token/test -u elastic:changeme
```
3.  Run fleet server in standalone
```shell
ELASTICSEARCH_CA_TRUSTED_FINGERPRINT=notused ELASTICSEARCH_SERVICE_TOKEN=<TOKEN_CREATED_BEFORE> ELASTICSEARCH_HOSTS=http://localhost:9200  go run main.go
```
4. Get the status and check it's healthy `http GET http://127.0.0.1:8220/api/status`
5. Create a policy in Kibana and  it's still healthy `http GET http://127.0.0.1:8220/api/status`

[Fleet] Fleet server standalone should be healthy before .fleet-policies is created

---

NOTICE.txt
go.mod
go.sum
internal/pkg/config/instrumentation.go
internal/pkg/config/instrumentation_test.go
internal/pkg/config/output.go
internal/pkg/config/output_test.go

Rename secret files attributes to use `_path` suffix to be consistent with existing naming conventions in the elastic-agent

Rename secret file attributes to use path suffix

---

internal/pkg/config/output.go

Cloud deployments for latest snapshot are broken with: `Error: service_token is undefined accessing config`.
Remove validation for service_token value from config spec
Run `make build-and-push-cloud-image`
Deploy with
```
curl -XPOST "https://public-api.qa.cld.elstc.co/api/v1/deployments?validate_only=false" -H "Authorization: ApiKey $API_KEY" -H "kbn-xsrf: reporting" -H "Content-Type: application/json" -d'
{
"resources": {
"integrations_server": [
{
"elasticsearch_cluster_ref_id": "main-elasticsearch",
"region": "gcp-us-central1",
"plan": {
"cluster_topology": [
{
"instance_configuration_id": "gcp.integrationsserver.n2.68x32x45.2",
"zone_count": 1,
"size": {
"resource": "memory",
"value": 1024
}
}
],
"integrations_server": {
"version": "8.8.0-SNAPSHOT",
"docker_image": …
```

Remove service token from output validation

---

.buildkite/hooks/post-checkout
.buildkite/hooks/pre-checkout
.buildkite/pull-requests.json

The pre-checkout hook is only working on the agent level and not in the repo scope.
In order to have working the option to use the merge commit of the PR I am migrating the post-checkout script that we used in elastic-package
Using the `use_merge_commit` instructs the bot to trigger Buildkite with the `ref/pull/{id}/merge` sha. Which is not reachable if you have not fetched the `refs/pull*`. 
Until we fix this with the bot, this PR changes the setting of the bot, and adds a hook that would take care of merging the target branch with the tip of the PR.

Replace pre-checkout with post-checkout

---

catalog-info.yaml

Duplicated builds are run in Buildkite triggered by the webhook and by the bot (buildkite-pr-bot)
This PR adds the settings `filter_enabled` and `filter_condition` to filter out the builds from PRs triggered by the webhook.
NOTE: this file was using `CRLF` as for the termination line (windows), updated to use `LF` as the other files in the repository.

Add filter_condition to avoid duplicated builds

---

internal/pkg/server/fleet.go
internal/pkg/server/fleet_test.go

Allow to enabled instrumentation through environment variable through `ELASTIC_APM_ACTIVE` environment variables
```
ELASTIC_APM_ENVIRONMENT=dev ELASTIC_APM_ACTIVE=true ELASTIC_APM_SERVICE_NAME=fleet-server ELASTIC_APM_SECRET_TOKEN=<TOKEN> ELASTIC_APM_SERVER_URL=<SERVER_URL> ./main
```

[Fleet] Allow to enable instrumentation through environment variable

---

README.md
changelog/fragments/1684151814-fix-action-seq-no.yaml
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/checkin/bulk.go
internal/pkg/checkin/bulk_test.go

Bugfix
Fix for a bug noticed in upgrades, where the upgrade action is the first action (`_seq_no:0`), and the agent doesn't get the action delivered on the next checkin if it misses the first checkin.
In `resolveSeqNo`, the agent's `action_seq_no` was incorrectly overwritten with 0 if the `ackToken` was not provided, which is the case for the first action.
In this case the agent doesn't get the action with `seq_no:0`, as Fleet Server considers it already delivered.
The agent should keep `action_seq_on:-1` until it gets an action delivered.
The overwrite is also wrong after Fleet Server restart, where the `ackToken` is empty (if I understand this correctly).
- Start a fresh ES, kibana, fleet-server (no actions created before)
- Enroll 1 drone with horde
- restart fleet-server
- trigger an …

fix for action_seq_no being overwritten with 0

---

.github/CODEOWNERS

We kept both teams as code owners when the Fleet team initially took over as owners of Fleet server. The Elastic Agent team's review hasn't been necessary for a while now, so I'm removing us as code owners. You can still ping us for opinions where needed.

Remove Elastic Agent control plane team as code owner.

---

version/version.go

Reverts elastic/fleet-server#2720.
E2E tests are failing since this change, it seems they require a 8.10 SNAPSHOT, that is not available yet.

Revert "Bump the version on main to 8.10.0"

---

.buildkite/pipeline.yml

The partial migration of the Jenkins pipeline to the Buildkite pipeline. 
Migrating the "Release - Package Registry Distribution" part
Instead the https://github.com/elastic/fleet-server/pull/2724, only changes according to the "Release - Package Registry Distribution" stage
It doesn't be checked locally, that's why it's a partial "step by step" migration
The Buildkite pipeline will be triggered by this PR and we will see the result
**Pipeline steps:**

add the trigger package-registry pipeline

---

internal/pkg/api/handleFileDelivery.go
internal/pkg/api/handleFileDelivery_test.go
internal/pkg/api/handleUpload_test.go
internal/pkg/file/delivery/delivery_test.go
internal/pkg/file/delivery/es.go

This is a manual backport of #2692, since it was merged in between creating the 8.9 branch, and setting up of the automatic backport stuff.

[8.9](backport #2692) Adds delivery module tests

---

Makefile

Try to reduce flakiness in E2E tests in Buildkite.
Increase `go test` timeouts.
Go tests default timeout is 10 minutes, and current E2E tests are taking around this time in buildkite, even when they pass:
When they fail, they are failing on different tests, but always with:
```
panic: test timed out after 10m0s
```
```
make test-e2e
```

Increase e2e tests timeout

---

.buildkite/pipeline.yml

Fix docker publish step in buildkite
The if condition to build the docker image was not met 
It seems according to buildkite doc that `BUILDKITE_PULL_REQUEST ` should be false if it's not a pull request and not an empty string

[Fleet] Fix docker publish step in buildkite

---

.buildkite/scripts/dra_release.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/236#018995a5-441f-40a1-9d52-401a2d8ca320
migrate release manager dependencies from `./dev-tools/run_with_go_ver` to the `dra_release.sh` script because the` ./dev-tools/run_with_go_ver` is still used

migrate release manager dependencies

---

.buildkite/scripts/dra_release.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/238#01899615-c3ef-4cef-b1f4-ea216c11b8bc
change the current folder for the release script

fix the folder_path issue

---

.buildkite/scripts/dra_release.sh
.buildkite/scripts/release-manager.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/240#0189966d-f773-4479-be35-7913b0e5f9db
add `cd ${WORKSPACE}` to the release-manager script

add path to release-manager script

---

.buildkite/scripts/dra_release.sh

fix the issue: https://buildkite.com/elastic/fleet-server-package-mbp/builds/242#018996d2-44d7-40e7-b368-59349dc25866
add `export ${WORKSPACE}` 

add export WORKSPACE

---

changelog/fragments/1690563780-Add-kafka-output-type-for-agent-policies.yaml
internal/pkg/policy/policy_output.go
internal/pkg/policy/policy_output_test.go

fleet-server gives an error if kafka appears an the output type in an agent policy.
Add `OutputTypeKafka` to policy output as a nop similar to logstash handling.
- Relates https://github.com/elastic/elastic-agent-shipper/issues/116

Add output type kafka to agent policies

---

internal/pkg/api/handleEnroll.go
internal/pkg/api/handleEnroll_test.go

Resolve #2877 
Fix an issue when enabling static enrollement tokens it was disabling support for regular db enrollment tokens.
That PR fix that and add a unit test to cover that scenario.
* Add some static tokens to your fleet server config
* Create a policy in the fleet UI and check you can enroll agents into that policy.

[Fleet] Fix static enrollment tokens blocking db enrollemnt tokens

---

.buildkite/hooks/pre-exit
.buildkite/scripts/common.sh

Fix the GCP credentials variable name according to the doc: https://cloud.google.com/docs/authentication/application-default-credentials#GAC
remove the extra "S" symbol
It tested in the other repository

fix the GCP credentials variable name

---

version/version.go

Fix human error causing wrong version numbers.

Fix branch version number

---

.buildkite/pipeline.yml

Update condition to execute Downstream package step, so it runs when a branch is updated.
It should not be executed in the context of Pull Requests nor tags.
Branches executed are filtered/configured at: https://github.com/elastic/fleet-server/blob/d2faa28c5ee3be5e333dcced708c936745296cb4/catalog-info.yaml#L44C1-L44C1

[buildkite] Update condition for downstream package step

---

.buildkite/pipeline.yml

Adding this branch setting to the buildkite pipeline will allow us to run the DRA scripts that are part of the same branch.

Add branch setting to pipeline

---

catalog-info.yaml

Fix https://github.com/elastic/fleet-server/pull/2909
Renamed the pipeline file and should be updated in catalog-info.yaml

fix catalog-info

---

.buildkite/pipeline.tests-qa.yaml
.buildkite/pipeline.tests-staging.yaml

Fix quality gate as they should use fleet-server as service name

update service to fleet-server

---

.buildkite/pipeline.tests-qa.yaml
.buildkite/pipeline.tests-staging.yaml
internal/pkg/logger/ecs.go
internal/pkg/logger/logger.go

Found that check error logs qg is failing as it is [using](https://github.com/search?q=repo%3Aelastic%2Fserverless-quality-gates%20SERVICE_TYPE_FIELD&type=code) `service.type` field by default to find fleet-server logs, which is not populated right now.
Using `service.name` instead.
Tested manually here: https://buildkite.com/elastic/serverless-quality-gates/builds/1182#018a603e-930f-4f87-b8d0-95e6524f21b7
```
$ ./observability/check-error-log-percentage.sh
--
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 100  1001  100   296  100   705    279    666  0:00:01  0:00:01 --:--:--   947
  | Calculated error percentage: 1
```

using `service.name` for check error logs

---

internal/pkg/server/fleet_integration_test.go

Fix flakey test
Fix flakey test my making it less concurrent and adding a wait time to try to ensure config changes are propogated
- Closes #2953

Fix TestServerInstrumentation with timeout

---

internal/pkg/server/fleet_integration_test.go

Fix flaky instrumentation test.
Fix flaky instrumentation test by changing the order of what is tested. Start with APM disabled, then test that traces are sent once it's enabled.
With the new monitor and coordinator transactions the fleet-server will start sending APM data almost immediately, these traces appear to be batched/streamed by the APM agent making it very dependent on timing to detect when the agent is disabled in the previous test case. By changing the order it should now run reliably.
`make test-int`
- Closes #2953

Fix flaky instrumentation test

---

version/version.go

Update version to 8.10.1

---

.buildkite/pipeline.tests-qa.yaml
.buildkite/pipeline.tests-staging.yaml

PR https://github.com/elastic/fleet-server/pull/2978 introduce filtering on service version but for this to work correctly we need to configure `SERVICE_REPOSITORY` to use the correct docker image for fleet server

[Fleet] Fix quality gates to use correct docker image

---

changelog/fragments/1696358866-Add-action-dispatcher-rate-limiter.yaml
fleet-server.reference.yml
internal/pkg/action/dispatcher.go
internal/pkg/action/dispatcher_test.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/config/env_defaults.go
internal/pkg/config/limits.go
internal/pkg/config/timeouts.go
internal/pkg/server/fleet.go

Small containers OOM when issuing updates to many clients, this could be mitigated by adding a rate limiter and using a pool for the gzip writter.
Add a sync.Pool to share gzip writers among all resquests in order to avoid new gzip.Writer allocations. Each writer allocation is around 1.2MB and is a limiting factor of hitting larger scales. Add action dispatch limiter to control how quickly the checkin endpoint writes responses in order to make better use of the writer pool.
- ~~I have or intend to scale test my changes, ensuring it will work reliably with 100K+ agents connected.~~ 10k test for serverless complete

Add ActionLimit and a gzip writer pool to handle checkin responses

---

changelog/fragments/1697136150-Fix-bulker-error-message-attribute.yaml
internal/pkg/bulk/opApiKey.go
internal/pkg/bulk/opBulk.go
internal/pkg/bulk/opRead.go
internal/pkg/bulk/opSearch.go

Some error logs produced specifically by the bulker are not ECS complient
Rename the "err" attribute to "error.message"
- Closes #3033

Fix bulker error attributes to be ECS complient

---

Makefile
README.md
changelog/fragments/1697230491-Relax-version-checks-in-snapshot-builds.yaml
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/userAgent.go
internal/pkg/api/userAgent_test.go
internal/pkg/api/verConst.go
internal/pkg/api/verConst_snapshot.go
internal/pkg/api/verConst_snapshot_test.go

Automated testing stalls for a few days when we release a new minor version.
Relax version checking when a SNAPSHOT binary of the fleet-server is built.
Version checking is relaxed to allow the minor version to be ahead by one.
If the fleet-server is running `X.Y.Z`, it allows clients of `X.Y+1.Z` to communicate.
`go test -v -tags=snapshot ./...`
Example output:
```
--- PASS: TestVersionConstraint (0.00s)
--- PASS: TestVersionConstraint/8.0.0 (0.00s)
--- PASS: TestVersionConstraint/8.1.0 (0.00s)
--- PASS: TestVersionConstraint/8.2.0 (0.00s)
PASS
```
- ~~I have included fail safe mechanisms to limit the load on fleet-server: rate limiting, circuit breakers, caching, load shedding, …

Relax version checks for snapshot builds

---

.buildkite/pipeline.yml

Package-Registry pipeline is not triggered if other steps are failing
Example of build where this step was not triggered: https://buildkite.com/elastic/fleet-server/builds/2186
Allow to be executed the trigger of package-registry pipeline without any dependencies on other steps.
As part of this PR, checking how it was configured Jenkins, it has been updated trigger steps to be asynchronous:
- https://github.com/elastic/fleet-server/blob/396d745bc1081190ff5912dcf0b05a266fe56f6a/.ci/Jenkinsfile#L215
-https://github.com/elastic/fleet-server/blob/396d745bc1081190ff5 …

[Buildkite] Allow failures to triggering package-registry job

---

changelog/fragments/1697650203-Add-missing-headers-to-openapi-spec.yaml
internal/pkg/api/api.go
internal/pkg/api/apiVersion.go
internal/pkg/api/openapi.gen.go
pkg/api/client.gen.go
pkg/api/doc.go
pkg/api/types.gen.go
pkg/api/versions/2023_06_01/api/client.gen.go
pkg/api/versions/2023_06_01/api/doc.go
pkg/api/versions/2023_06_01/api/openapi.yml
pkg/api/versions/2023_06_01/api/types.gen.go
testing/e2e/api_version/client_api_2023_06_01.go
testing/e2e/api_version/client_api_current.go

`Elastic-Api-Version` and `X-Request-Id` headers are not defined as part of responses for fleet-server
Add doc.go files for minimal information on generated client apis (what they are generated from).
Add missing headers to all req/resp in the openapi spec for the current implementation in `model/openapi.yml`.
Add an `openapi.yml` spec file for the `2023-06-01` based off commit 1d28f4ca4ec62f940771e5eb72b77699d256525f with the missing headers (and version defined in the spec). Correct the directory name for the versioned client.

Add Elastic-Api-Version and X-Request-Id headers in openapi spec

---

internal/pkg/apikey/apikey.go
internal/pkg/apikey/apikey_test.go

Resolve #3046  
Improve error handling when enrollemnt token or api key during checkin is not a valid base64 token, and return a 400 instead of a 500.
This is covered by a new unit test

[Fleet] Improve error handling for invalid base64 token

---

changelog/fragments/1698420960-output-secrets.yaml
internal/pkg/policy/parsed_policy.go
internal/pkg/policy/policy_output.go
internal/pkg/policy/secret.go
internal/pkg/policy/secret_test.go

Resolve #2966 
Add support for output secrets.
Implementation details, if we found anything under `secrets` for an output fleet server will retrieve the associated secret and put it under the same path in the resulting output, this should be future proof and allow us to support new output secrets without any change to fleet server.
Example `secrets: { "password": {"id": "TEST"} }` => `{ "password": "retrieved_password_for_TEST_id"}`

[Fleet] Support output secrets

---

internal/pkg/api/error.go

Resolve https://github.com/elastic/fleet-server/issues/3068
Better handling of policy not found error for static tokens, return a 400 instead of 500.
as it's a temporary error that could be fixed by a user (or by the preconfiguration) by creating the correct policy.
Automated test, the policy not found is already handled and there is a unit test is here, not sure we should add a e2e test for that.

[Fleet] Better handle policy not found error for static tokens

---

changelog/fragments/1699380976-Replace-any-secret-ref-in-input-map.yaml
internal/pkg/policy/secret.go
internal/pkg/policy/secret_test.go

Secret references are being missed as they can be embedded in sub objects or arrays as part of the input (or stream) object.
Use a more generic approach to go through input objects and replace secret references.
`make test` for the unit test that was added.
Or follow the integration setup instructions in #3083 
- Closes #3083

Replace all secret references in input map

---

.buildkite/pipeline.yml

Error in the SonarQube step:
`ERROR: Test report can't be loaded, file not found: '/buildkite/builds/bk-agent-prod-k8s-1699483250115927686/elastic/fleet-server/build/test-unit.out.xml', ignoring this file.`
It's tested in the https://github.com/elastic/integrations/pull/8464
-

add uploading the test-unit.out.xml artifact

---

internal/pkg/bulk/bulk_test.go

Tests are flaky
Remove test logger that is being used after test terminates
`make test-unit`
- Closes #3134

Remove logger and timings from tests

---

changelog/fragments/1702574888-Drain-HTTP-connections-on-shutdown.yaml
fleet-server.reference.yml
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleStatus.go
internal/pkg/api/server.go
internal/pkg/checkin/bulk.go
internal/pkg/config/config_test.go
internal/pkg/config/timeouts.go
internal/pkg/profile/profile.go
internal/pkg/profile/profile_test.go
internal/pkg/server/fleet.go
internal/pkg/server/fleet_integration_test.go

Checkin API long-poll connections terminate with an error when the server needs to shut down (providing a 5xx to the client).
Use the Shutdown method with a timeout to try to gracefully shutdown
HTTP connections. If the server times out while attempting to drain the
connections, connections are forced closed. If there is a long-polling
checkin request, the server should send a 200 response with the ack
token used in the request (same behaviour as the poll completing
normally).
- Closes #2902

Use Shutdown to gracefully halt HTTP servers

---

.buildkite/pull-requests.json

Pull Requests created by dependabot do not trigger builds in Buildkite.
Added `dependabot[bot]` user into the allowed users to run builds in Pull Requests.

[Buildkite] Add dependabot as a user to run builds in Pull Requests

---

NOTICE.txt
internal/pkg/api/openapi.gen.go
internal/pkg/api/openapi_spec_test.go
model/openapi.yml
pkg/api/types.gen.go

Backport https://github.com/elastic/fleet-server/pull/3177 to 8.12

[8.12] added download_rate to openapi (#3177)

---

dev-tools/integration/.env

<Actions>
<p>1 file(s) updated with &#34;$1=8.13.0-pjcmn9wb-SNAPSHOT&#34;:&#xA;&#x9;* dev-tools/integration/.env&#xA;</p>
</details>
<a href="https://github.com/elastic/fleet-server/actions/runs/7398912560">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] update elastic stack version for testing 8.13.0-toucn398-SNAPSHOT

---

fleet-server.reference.yml
internal/pkg/api/server_test.go
internal/pkg/es/client_test.go
internal/pkg/monitor/mock/monitor.go
internal/pkg/testing/certs/certs.go

unit tests for mTLS support.
Add the mTLS attributes that fleet-server can use to connect to Elasticsearch, and that clients can use to connect to fleet-server in the fleet-server.reference.yml doc. Add unit tests to ensure that mTLS works as expected in the internal es and api packages.

Add mtls attributes to reference and unit tests

---

internal/pkg/policy/secret.go
internal/pkg/policy/secret_test.go

Fix issue with package policy secrets not being replaced properly when multiple secrets were in a variable.
Improved replace logic to replace all secret refs in a variable value.
- Build akamai package with enabling secrets from here: https://github.com/elastic/integrations/pull/8725/files [akamai-2.22.0.zip](https://github.com/elastic/fleet-server/files/13840673/akamai-2.22.0.zip)
- upload package to local kibana
```
curl -XPOST -H 'content-type: application/zip' -H 'kbn-xsrf: true' http://localhost:5601/api/fleet/epm/packages -u elastic:changeme --data-binary …
```

fix multiple secret ref replace

---

internal/pkg/bulk/bulk_integration_test.go
internal/pkg/bulk/opSearch.go
internal/pkg/bulk/opt.go
internal/pkg/dl/policies.go

Ignore not yet created .fleet-policies index to avoid returning 500 when that index do not exists yet.
run a fleet server with `.fleet-policies` not yet created and static tokens 
```
inputs:
- type: fleet-server
policy.id: "${FLEET_SERVER_POLICY_ID:fleet-server-policy}"
server:
static_policy_tokens:
enabled: true
policy_tokens:
- policy_id: 901b70f0-fefa-11ed-aa5e-5974b0535e80
token_key: abcdefg
```
Try to enroll an agent  it should return a 400 instead of a 500 previously
```
curl --request POST \
--url http://localhost:8220/api/fleet/agents/enroll \
--header 'Authorization: ApiKey MDEyMzQ6YWJjZGVmZw==' \
--header 'Content-Type: application/json' \
--header 'User-Agent: elastic agent 8.9.0' \
--header 'kbn-xsrf: xx' \
--data '{
"type": "PERMANENT",
"metadata": {
"local": {
"host": { …
```

[Fleet] Ignore not yet created .fleet-policies index

---

testing/e2e/stand_alone_test.go
testing/e2e/statusProxy.go
testing/e2e/testdata/stand-alone-http-proxy.tpl

We have observed the fleet-server crashing if a 429 is returned when fleet-server initializes.
Add e2e tests to for this behaviour to ensure no regressions occur.
- ~~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)~~
- Closes #3205

Add e2e test for timeout and 429 on startup

---

changelog/fragments/1705963635-Stricter-validation-for-required-checkin-API-attributes.yaml
internal/pkg/api/handleCheckin.go
internal/pkg/server/fleet_integration_test.go
testing/e2e/api_version/client_api_2023_06_01.go
testing/e2e/api_version/client_api_current.go

Checkin endpoint does not check for required attributes
Add validation to make sure that status and message are present in the checkin request body.
- Closes #2420

Stricter validation for required checkin API attributes

---

changelog/fragments/1706127160-Change-response-codes-for-elasticsearch-failures-to-503.yaml
internal/pkg/api/error.go
internal/pkg/api/error_test.go

fleet-server returns a 500 if a call to elasticsearch fails
Change returned status code to 503 to indicate a temporary problem.
- Closes #2852

Change response codes for elasticsearch failures to 503

---

internal/pkg/api/handleAck.go
internal/pkg/api/handlePGPRequest.go
internal/pkg/bulk/helpers.go

Use io.Copy  or a json decoder instead of io.ReadAll on bulker/API.
Copying to a bytes.Buffer results in fewer allocations then ReadAll.

remove io.ReadAll from bulker and API endpoints

---

main.go

Updates references to the new release 7.17.19.
Merge after the release 7.17.18.

[Release] Update version to 7.17.19

---

internal/pkg/api/server_test.go

Pass a test logger with the context used in the mtls unit tests.
Tests are flakey more logs would be useful to debug
- Relates #3266

Pass logger to mtls server in tests

---

changelog/fragments/1707481003-fix-upgraded-at.yaml
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/model/schema.go
model/schema.json

Agent was never upgradeable again after an upgrade to 8.12.0
When `upgrade_details: null` comes from the agent doc, the logic incorrectly supposed it has a value, and set `upgraded_at: now`. This resulted the agent never being upgradeable again on the UI (as it is not allowed to upgrade again within 10 minutes of an upgrade).
Upgraded the schema, so that the `null` value is correctly translated to `nil`, and the condition in `handleCheckin` can check for `nil`.
- Start a stack at least 8.12.1 or latest.
- enroll an agent 8.11.4 or older
- upgrade to 8.12.0
- wait 10 minutes so that the watcher period ends
- expect the agent to be upgradeable again to 8.12.1
Closes https://github.com/elastic/fleet-server/issues/3263

fix process upgrade details when null

---

internal/pkg/policy/monitor.go

Follow up for https://github.com/elastic/fleet-server/issues/3239
Updated some remaining places to make revision idx logging consistent.

make revision idx log fields consistent

---

changelog/fragments/1702940211-Replace-policy-throttle-with-limiter.yaml
fleet-server.reference.yml
internal/pkg/action/dispatcher.go
internal/pkg/action/dispatcher_test.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/server_test.go
internal/pkg/config/defaults/lte10000_limits.yml
internal/pkg/config/defaults/lte20000_limits.yml
internal/pkg/config/defaults/lte2500_limite.yml
internal/pkg/config/defaults/lte40000_limits.yml
internal/pkg/config/defaults/lte5000_limits.yml
internal/pkg/config/defaults/max_limits.yml
internal/pkg/config/env_defaults.go
internal/pkg/config/limits.go
internal/pkg/policy/monitor.go
internal/pkg/policy/monitor_integration_test.go
internal/pkg/policy/monitor_test.go
internal/pkg/server/fleet.go

Reverts elastic/fleet-server#3255
Unified limiter is causing OOM issues in serverless pods during scale testing (upgrade actions)

Revert "Replace policy and action limiters with a checkin limiter"

---

changelog/fragments/1707852625-Prefer-elastic-agent-client-APMConfig-in-agent-mode.yaml
internal/pkg/server/agent.go
internal/pkg/server/agent_test.go

elastic-agent-client is now able to send APMConfig settings separately from expected config (similar to how the log level can be separated), but fleet-server is unable to use these settings.
Consume and prefer APMConfig from the expected input component while operating in agent mode over config in inputs[0].server.instrumentation.
- Closes #2868

Consume APMConfig from input units in agent mode

---

.mergify.yml

Merge as soon as 8.13 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821

backport: Add 8.13 branch

---

Makefile
dev-tools/cloud/Makefile
dev-tools/cloud/launch_cloud_e2e_tests.sh
testing/e2e/agent_container_test.go
testing/e2e/agent_install_test.go
testing/e2e/e2e_test.go

Disable the test suites that require elastic-agent and stop building the custom test image for e2e tests.

Disable all e2e tests that require elastic-agent

---

Makefile
dev-tools/cloud/docker/build.sh

Bumping fleet-server versions causes the cloude2e test to fail
Use the fleet-server binary version with snapshot flag when building the cloude2e test image instead of the stack version so fleet-server builds will not fail on version bumps.

Use fleet-server binary version for cloude2e images

---

changelog/fragments/1710319964-Allow-level:-trace-for-settings-actions.yaml
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/openapi.gen.go
model/openapi.yml
pkg/api/types.gen.go

Allow fleet to set trace level for logging
Allow the trace level to be set in settings actions.

Allow level: trace in settings action

---

.github/dependabot.yml

We don't use the `skip-changelog` label

Fix dependabot label

---

.buildkite/scripts/build_push_docker_image.sh

Failed docker publish on prs. After the last changes, the script tries to create a docker image tag with the name of the pr branch, which is invalid (probably because of `:`)
https://buildkite.com/elastic/fleet-server-perf-tests/builds/23#018e6605-24ea-4443-93bd-c67bc6a2b6b6
```
ERROR: invalid tag "docker.elastic.co/observability-ci/fleet-server:szwarckonrad:test-pipeline": invalid reference format
--
  | make: *** [Makefile:220: build-and-push-docker] Error 1
```
Only publish to branch name tag if not on a pr (e.g. 8.13)
Follow up after https://github.com/elastic/fleet-server/pull/3388

fix for docker image script

---

.buildkite/pipeline.tests-staging.yaml

Stop deployment if long standing deployment is not healthy in staging.
Enable synthetic monitor check in staging quality gates.
Configured as described here: https://docs.elastic.dev/serverless/qualitygates#synthetics-gate
Can only be verified after merged.
First the synthetic monitor pr should be merged.
Relates https://github.com/elastic/ingest-dev/issues/2861
Depends on https://github.com/elastic/synthetics-monitors/pull/90

enable synthetics test in staging quality gates

---

.gitignore
README.md

I was running into lsp errors while trying to work on e2e tests. The details of the errors are outlined in the PR itself. This made working on the testing package quite difficult as I was not getting any sort of completions or suggestions.  
One of the errors was due to the nested modules. Configuring go workspaces resolves this issue. I configured `go.work` on my machine and tried to make it work with the build steps as can be seen in this [PR](https://github.com/elastic/fleet-server/pull/3380); however, I couldn't resolve several issues. In this PR I added `go.work` and `go.work.sum` files to the `.gitignore` file and described how you can configure them. The second issue was due to the build constraints (eg. `//go:build e2e`). The solution for this is explained in the updated README. …

3379 lsp config documentation and gowork 2

---

internal/pkg/action/dispatcher.go
internal/pkg/policy/monitor.go

The scale tests is hitting some of the limit and logging this as errors seems to make the quality gates failling.
That PR should fix it by changing the log level
An example of a log message that will be logged as warning instead of error.

[Fleet] Change action and policy rate limiter error log level to warn

---

changelog/fragments/1711580899-fix-bad-request-status-code-checkin.yaml
internal/pkg/api/error.go
internal/pkg/api/error_test.go
internal/pkg/api/handleAck.go
internal/pkg/api/handleAck_test.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/handleEnroll.go
internal/pkg/api/handleEnroll_test.go
internal/pkg/api/handleUpload.go
internal/pkg/api/handleUpload_test.go
internal/pkg/server/fleet_integration_test.go
testing/e2e/api_version/client_api_current.go

Some of the fleet server endpoints return 500 errors when the handler runs into an error while validating the incoming request body. Handler should respond with 400 error code.
Added a new error type "BadRequestErr" to encapsulate the errors that may occur while validating a request body. Updated the error table to return a 400 status code HTTPErrResp.

3110 return 4xx errors instead of 5xx errors for bad requests payloads

---

.buildkite/pipeline.tests-staging.yaml

Synthetic monitor failed because it ran out of max poll: https://buildkite.com/elastic/serverless-quality-gates/builds/8566#018ea08d-fbf3-4e07-b5e4-257b53f9d290
```
2024/04/02 21:29:26 Still running with intermediate results:
========================= MonitorRun Statistics =====================
• serverless - fleet long standing check: {Current:up Checks:531 Up:526 Down:5}
[up up]
==================================================================
2024/04/02 21:30:56 Need to collect more results of [1] monitors...
2024/04/02 21:32:27 Need to collect more results of [1] monitors...
2024/04/02 21:33:57 Need to collect more results of [1] monitors...
2024/04/02 21:35:27 Need to collect more results of [1] monitors...
2024/04/02 21:36:57 Need to collect more results of [1] monitors... …
```

increase synthetic max poll

---

.github/dependabot.yml

These packages use to be released together, update them also together in single PRs.

Group dependabot updates of apm dependencies in single PRs

---

NOTICE.txt
go.mod
go.sum
testing/go.mod
testing/go.sum

Snapshots deployed have error logs stating:
```
tls renegotation support is an unknown type: int64 accessing 'output.elasticsearch.ssl.renegotiation'
```
Update elastic-agent-libs to version that supports uint64 and int64 unpacking
- Relates #3465

Update elastic-agent-libs to v0.9.4

---

Makefile
dev-tools/integration/docker-compose.yml
dev-tools/integration/get-elasticsearch-servicetoken.sh
dev-tools/integration/wait-for-elasticsearch.sh
internal/pkg/bulk/engine.go
internal/pkg/server/remote_es_output_integration_test.go

Resolve https://github.com/elastic/fleet-server/issues/3490
Fix remote ES client creation. the previous creation was only using the hosts and service token fields, making it impossible to create a client for a remote ES using self signed certificate. 
That PR fix that by creating a client with the correct config 
Create a remote ES to a self signed certificate and check the output is healthy and can generate API keys.
I updated the integration test to run a remote ES with ssl enabled.

Fix remote ES client to use ssl.* settings

---

.github/CODEOWNERS

This PR updates the default codeowners for this repository to `@elastic/elastic-agent-control-plane` so this team is automatically assigned as the default reviewers for any PRs created in this repository.

Update default codeowners

---

.buildkite/pipeline.yml

Missing trigger step in 7.17 to create docker distribution images with all the packages as in main or 8.* branches.
This PR backports these two PRs #2729 and #3043 adds the same step as in main branch to trigger the pipeline https://buildkite.com/elastic/package-registry-release-package-registry-distribution in charge of creating the docker distribution images.

[Buildkite] Add step to trigger release distribution pipeline

---

catalog-info.yaml

Update the catalog-info value in order for fleet-server to show up in the serverless release dashboard.
According to @zenitraM this change is required for fleet-server to show up in our release dashboard.

Add service-name for Serverless release

---

NOTICE.txt
changelog/fragments/1720021515-fix_download_rate.yaml
go.mod
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/metadata.go
internal/pkg/api/metadata_test.go

Relates https://github.com/elastic/ingest-dev/issues/3446
Elastic-agent are currently not sending download rate as a float but as a string with unit, while this is fixed on the agent side and for older agent, Fleet server should accept both format.
That PR does that, and return a 400 instead of a 500 when an error parsing meta happen.

[Fleet] Support download rate in string with unit format

---

changelog/fragments/1723590385-Add-audit-unenroll-API.yaml
fleet-server.reference.yml
internal/pkg/api/api.go
internal/pkg/api/error.go
internal/pkg/api/handleAudit.go
internal/pkg/api/handleAudit_test.go
internal/pkg/api/metrics.go
internal/pkg/api/openapi.gen.go
internal/pkg/api/router.go
internal/pkg/api/router_test.go
internal/pkg/api/server.go
internal/pkg/api/server_test.go
internal/pkg/config/defaults/lte10000_limits.yml
internal/pkg/config/defaults/lte20000_limits.yml
internal/pkg/config/defaults/lte2500_limite.yml
internal/pkg/config/defaults/lte40000_limits.yml
internal/pkg/config/defaults/lte5000_limits.yml
internal/pkg/config/defaults/max_limits.yml
internal/pkg/config/env_defaults.go
internal/pkg/config/limits.go
internal/pkg/dl/constants.go
internal/pkg/model/schema.go
internal/pkg/server/fleet.go
internal/pkg/server/fleet_integration_test.go
internal/pkg/testing/setup.go
model/openapi.yml
model/schema.json
pkg/api/client.gen.go
pkg/api/types.gen.go
testing/e2e/api_version/client_api_current.go

Uninstalled agents appear as offline in the fleet UI.
Add `/api/fleet/agents/:id/audit/unenroll` API that an elastic-agent or Endpoint process may use to annotate the agent document so the agent may appear with a different status.
[RFC here](https://docs.google.com/document/d/1gYbsGfvjc7NhbURwYNqEl25ouar81nZ_8bkpsi0Dc6Y/edit#heading=h.pfm1mse74cxb)
Changes are:
- 409 responses will include a JSON body to be consistent with other errors
- Successfull requests will alter the following agent document attributes:
- `audit_unenrolled_time` - time from request
- `audit_unenrolled_reason` - reason from request
- `unenrolled_at` - server current time UTC
- `updated_at` - server current time UTC (new)
- ~~`active` - set to `false` (new)~~ removed change, was causing the api key auth to fail …

Add `/api/fleet/agents/:id/audit/unenroll` endpoint

---

.github/workflows/bump-elastic-stack-snapshot.yml

⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been deprecated in favor of 
https://github.com/elastic/oblt-actions.
If there are any questions, please reach out to the @elastic/observablt-ci

github-action: use oblt-actions/elastic/active-branches

---

.mergify.yml

When the `main` branch switches over to `9.0`, we will want most PRs that are merged into `main` to also be backported to `8.x`. This PR makes this process easier by automatically adding the `backport-8.x` label to all PRs targeting the `main` branch.
The exceptions will be PRs for changes that should _only_ be present in `9.0`. For such PRs, authors should simply remove the `backport-8.x` label from their PR.

Automatically label PRs to `main` with `backport-v8.x`

---

Makefile
dev-tools/e2e/build.sh

e2e tests fail on version change
use the version from `version/version.go` instead of the docker image label when searching for the cover enabled binary to replace the fleet-server component in the image.
- Closes #3886

Fix version source when making e2e agent image

---

.github/workflows/golangci-lint.yml
Makefile
internal/pkg/api/handleAck.go
internal/pkg/api/handleArtifacts.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleEnroll.go
internal/pkg/api/handleStatus.go
internal/pkg/api/openapi_spec_test.go
internal/pkg/bulk/opMulti.go
internal/pkg/cache/cache.go
internal/pkg/config/env_defaults.go
internal/pkg/dl/migration_integration_test.go
internal/pkg/file/cbor/chunk.go
internal/pkg/file/cbor/chunk_test.go
internal/pkg/file/uploader/upload_test.go
internal/pkg/logger/http.go
internal/pkg/monitor/monitor.go
internal/pkg/policy/policy_output_integration_test.go
internal/pkg/scheduler/scheduler.go
internal/pkg/server/fleet_integration_test.go
internal/pkg/testing/port.go

Go version update to 1.23.x causes a lot of noise in the linter.
Update the linter used to 1.65.0, fix new issues.
The most common is a gosec G115 issue that attempts to find where we can have overflows caused by casting to/from int/uint (or int/int32).
Most of these are silenced as they would not be able to occur and there are false positives in the detector, see https://github.com/securego/gosec/issues/1212

Update golangci-lint version

---

Dockerfile.build
Makefile
dev-tools/e2e/docker-compose.yml
dev-tools/integration/docker-compose.yml

Allow tests to run off arm platforms
Remove hard-coded `amd64` values from test setup
`make test-int` or `make test-e2e`
- Relates #3620

Fix test setup to run on ARM instances

---

.buildkite/pipeline.yml

This PR reverts https://github.com/elastic/fleet-server/commit/3750daa2854ba95e37ee8e4842e6fec9d9bc0f67 as it is now possible to create `9.0.0-SNAPSHOT` deployments on ESS prod in the CFT region.
Resolves #3920

Unskip cloud E2E tests

---

internal/pkg/bulk/bulk_integration_test.go

As described in https://github.com/elastic/fleet-server/pull/3971#issuecomment-2394723142, Elasticsearch's Bulk API keeps changing the response code from `500` to `400`.  As such, we need to keep updating the `Invalid utf-8` bulk indexing integration test to match.  While the permanent fix to this issue will be done in Elasticsearch (see https://elasticco.atlassian.net/browse/ES-9711), this PR updates the test to accept an alternate error from Elasticsearch as a workaround.
By adding an `AltError` field to the test case struct, allowing the `Invalid utf-8` test …

Allow bulk integration tests to accept alternate errors from Elasticsearch

---

.buildkite/hooks/pre-command
.buildkite/pipeline.yml

Add the test collector plugin to enable Buildkite test analytics. Test results will be shown here after main branch pipeline runs: https://buildkite.com/organizations/elastic/analytics/suites/fleet-server
Closes https://github.com/elastic/ingest-dev/issues/3916

Add test collector plugin for Buildkite analytics

---

version/version.go

Update version to next minor 8.17.0.
Merge after create the new release branch.

Bump the version on `8.x` to `8.17.0`

---

internal/pkg/bulk/bulk_integration_test.go

This PR expects only a 400 HTTP response code from the Elasticsearch bulk API in integration tests when invalid index name is specified.  Concretely, it removes the `AltErr` field temporarily introduced in https://github.com/elastic/fleet-server/pull/4001 which was allowing the tests to accept an alternate error from Elasticsearch.
Related: https://github.com/elastic/elasticsearch/pull/114869

[Integration testing] Remove AltErr and only expect 400 from ES bulk API

---

changelog/fragments/1728652985-Dont-fail-checkin-if-upgrade-action-not-found.yaml
internal/pkg/api/handleCheckin.go
testing/e2e/api_version/client_api_current.go

Relates https://github.com/elastic/ingest-dev/issues/4223
We're investigating an issue in a serverless project where Fleet Server keeps throwing 500 on agent checkin because the agent has upgrade details but the action id they refer to is not found.
Modify `Checkin.processUpgradeDetails` so that checkin does not fail in this scenario and log a warning instead.

Don't fail checkin if agent has upgrade details with no action

---

internal/pkg/server/agent.go
internal/pkg/server/agent_test.go

This PR introduces support for APM sample rate using the values provided by elastic-agent though the control protocol
Added a check for a value of transacton sampling in `apmConfigToInstrumentation` (it's an optional float32) and formatted the vale as a string to be included in the instrumentation copnfig.

Support sampling rate in APM configuration

---

dev-tools/cloud/terraform/main.tf

What it says on the tin. 
https://registry.terraform.io/providers/elastic/ec/0.12.1

Update version of elastic/ec terraform provider to latest

---

dev-tools/cloud/terraform/main.tf

This PR updates the deployment template ID used to spin up deployments in ESS for Cloud E2E tests.  The deployment template ID being used has been [deprecated](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html) and continuing to use it is making the Cloud E2E tests fail like so:
```
ec_deployment.deployment: Creating...
--
  | ╷
  | │ Error: failed creating deployment
  | │
  | │   with ec_deployment.deployment,
  | │   on main.tf line 46, in resource "ec_deployment" "deployment":
  | │   46: resource "ec_deployment" "deployment" {
  | │
  | │ api error: 10 errors occurred:
  | │ 	* deployments.elasticsearch_using_legacy_dt: The referenced deployment template in elasticsearch plan [gcp-io-optimized-v2] is no longer available.
  | │ 	* …
```

Replace deprecated deployment template ID

---

version/version.go

Updates references to the new release 8.16.1.
Merge after the release 8.16.0.

[Release] Update version to 8.16.1

---

.buildkite/pipeline.yml
testing/e2e/agent_install_test.go

This PR skips the following tests that depend on `8.18.0-SNAPSHOT` artifacts being available:
* `TestAgentInstallSuite` E2E test - depends on `elastic-agent-8.18.0-SNAPSHOT` artifact being available.
* `TestBaseE2ETestSuite` Cloud E2E test - depends on `8.16.0-SNAPSHOT` deployments being available in ESS.
This PR should be reverted as soon as the above artifacts become available.

Skip tests that depend on `8.18.0-SNAPSHOT` artifacts being available

---

cmd/fleet/main.go

Add version flag to standalone command, pass version to cobra, that will handle the `--version` flag

[Fleet] Add version flag

---

changelog/fragments/1732279064-Fix-server.address-field-in-HTTP-logs.yaml
internal/pkg/logger/http.go
internal/pkg/logger/http_test.go

`server.address` is empty in HTTP request logs.
Populate `server.address` using the interface associated with `http.LocalAddrContextKey`.
start a fleet-server and make an HTTP request.

Fix server.address field in HTTP logs

---

changelog/fragments/1733164563-Refactor-API-struct-constructor.yaml
internal/pkg/api/api.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/handleStatus.go
internal/pkg/api/handleStatus_test.go
internal/pkg/api/server.go
internal/pkg/api/server_test.go
internal/pkg/server/fleet.go

Refactor API constructor to use functional opts instead of a long list of pointers.
- Closes #3823

Refactor API struct constructor

---

changelog/fragments/1733164018-Replace-use-of-context.TODO.yaml
cmd/fleet/main.go
internal/pkg/action/dispatcher.go
internal/pkg/api/handleArtifacts.go
internal/pkg/api/handleCheckin.go
internal/pkg/api/handleFileDelivery.go
internal/pkg/api/handleUpload.go
internal/pkg/api/metrics.go
internal/pkg/api/server.go
internal/pkg/bulk/engine.go
internal/pkg/cache/cache.go
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/env_defaults.go
internal/pkg/config/env_defaults_test.go
internal/pkg/file/uploader/finalize.go
internal/pkg/limit/listener.go
internal/pkg/profile/profile.go
internal/pkg/server/agent.go
internal/pkg/server/fleet.go
internal/pkg/server/fleet_integration_test.go
internal/pkg/state/reporter.go
internal/pkg/testing/esutil/datastream.go
internal/pkg/testing/esutil/esutil.go
internal/pkg/testing/esutil/ilm.go
internal/pkg/testing/esutil/index.go
internal/pkg/testing/esutil/template.go
internal/pkg/throttle/throttle.go
internal/pkg/throttle/throttle_test.go

Replace use of context.TODO and context.Background from most use cases
- Closes #3087

Replace most context.TODO calls, comment on other Background and TODOs

---

changelog/fragments/1733181546-Remove-race-in-remote-bulker-access.yaml
internal/pkg/bulk/bulk_remote_output_test.go
internal/pkg/bulk/engine.go

Remove a race condition/bug that may occur when remote ES outputs are used.
Use the `remoteOutputMutex` whenever accessing the `bulkerMap`.
Change `GetBulkerMap` to return a copy of the map so that remote output health will not conflict with adding/removing a bulker from the map.
- Closes …

Remove race condition when accessing remote bulker map

---

internal/pkg/config/config.go
internal/pkg/config/config_test.go

Static tokens and (potentially) custom http headers can expose secrets in diagnostic bundles.
Redact sensitive values within the `Config.Redact()` call,

Redact static tokens and custom http headers

---

changelog/fragments/1734380253-Audit-unenroll-does-not-set-unenrolled_at-attribute.yaml
internal/pkg/api/handleAudit.go
internal/pkg/api/handleCheckin.go
internal/pkg/checkin/deleteAuditFieldsOnCheckin.painless
internal/pkg/server/fleet_integration_test.go

On systems where defend is running and may report as orphaned during an upgrade process, the `unenrolled_at` attribute will be set and will prevent future upgrade commands from being issued through Kibana.
Do not set the `unenrolled_at` attribute when the audit/unenroll API is called.
Remove the `unenrolled_at` attribute if it's set during checkin.
- ~~I have made …

Audit unenroll should not set unenrolled_at attribute

---

.buildkite/pipeline.yml
testing/e2e/agent_install_test.go

Reverts elastic/fleet-server#4214 as:
* `elastic-agent-8.17.1-SNAPSHOT` artifact is now available, and
* it's now possible to create `8.17.1-SNAPSHOT` deployments in the ESS production CFT region.

Revert "Skip tests that depend on `8.17.1-SNAPSHOT` artifacts being available"

---

.buildkite/pipeline.yml
testing/e2e/agent_install_test.go

Reverts elastic/fleet-server#4133 as it's now possible to create `8.18.0-SNAPSHOT` deployments in the ESS production CFT region.

Revert "Skip tests that depend on `8.18.0-SNAPSHOT` artifacts being available"

---

internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/testdata/tls.yml
internal/pkg/config/testdata/tls10.yml

Avoid a planned breaking change for tlscommon versions
Call `tlscommon.SetInsecureDefaults` in config init to reset version numbers to currently supported versions.
- ~~I have added an entry in `./changelog/fragments` …

Call tlscommon.SetInsecureDefaults

---

changelog/fragments/1735593163-Remove-auth-requirement-from-PGP-key-endpoint.yaml
internal/pkg/api/error.go
internal/pkg/api/handlePGPRequest.go
internal/pkg/api/openapi.gen.go
model/openapi.yml
pkg/api/client.gen.go
testing/e2e/api_version/client_api_current.go

Air gapped agents are unable to retreive PGP key from fleet-server.
Remove auth key requirement from PGP retrieval endpoint
- Closes #4255

Remove PGP endpoint auth requirement

---

changelog/fragments/1736277781-Remove-deprecated-policy_throttle.yaml
fleet-server.reference.yml
internal/pkg/config/limits.go
internal/pkg/policy/monitor.go
internal/pkg/policy/monitor_test.go

Remove deprecated policy_throttle config.
policy_limit should be used in 9.x releases

Remove deprecated policy_throttle config

---

.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/pipeline.package.mbp.yml
.buildkite/scripts/dra_release.sh
.buildkite/scripts/package.sh

This commits adds support for an optional $VERSION_QUALIFIER env var/build option in the packaging pipeline to allow building prerelease artifacts from staging.
* Support VERSION_QUALIFIER optional env var for prerelease builds
* Refactor packaging pipeline to allow staging builds from main (that indirectly allow testing this PR too with the additional `DRA_BRANCH` env var and skip snapshot builds when VERSION_QUALIFIER is present
* Remove unused VERSION and INFRA_REPO variables.
Using this PR and the pipeline https://buildkite.com/elastic/fleet-server-package-mbp with `pull/4328/merge` and options: 
```
DRA_BRANCH="main"
VERSION_QUALIFIER="alpha1"
```
results in a successful 9.0.0-alpha1 artifacts, example: https://buildkite.com/elastic/fleet-server-package-mbp/builds/1526
Also a test …

Allow use of version qualifier for staging artifacts

---

.buildkite/pipeline.package.mbp.yml
.buildkite/scripts/package.sh

This commit fixes a bug in #4328 running snapshot instead of staging for x86-64 and also ensures staging on main can be build when
VERSION_QUALIFIER is set.
- Closes https://github.com/elastic/ingest-dev/issues/4859

Allow staging build on main with version qualifier

---

.buildkite/pipeline.package.mbp.yml
.buildkite/scripts/version_qualifier.sh

To avoid manual invocations specifying the version qualifier for prereleases in this commit we leverage a centralized version of truth for the version qualifier.
Leverages a centralized source of truth version for the version qualifier.
Tested in BK only.
Links:
Snapshot build (9.0.0-SNAPSHOT): https://buildkite.com/elastic/fleet-server-package-mbp/builds/1573#0194b7fc-3802-4341-aa12-7d44f88dcdad ✅
Staging build (9.0.0-beta1): https://buildkite.com/elastic/fleet-server-package-mbp/builds/1573#0194b7fc-3803-4fac-960b-af7edc21453f ✅

Use centralized version qualifier

---

dev-tools/e2e/kibana.yml
dev-tools/integration/.env
testing/e2e/agent_install_test.go
testing/e2e/const.go
testing/e2e/const_windows.go

It's hard to run e2e tests on a host that has elastic-agent installed.
Use the `--develop` flag to install an agent in the development namespace
Change version in `dev-tools/integration/.env` to `9.1-SNAPSHOT`
`make test-e2e`

Use --develop flag for agent install e2e tests

---

dev-tools/integration/.env

The automated version bump is stuck on 8.18.x because the artifacts API is out of date. We possibly need to move away from the artifacts API as we have elsewhere, this will at least unstick the tests.
https://storage.googleapis.com/artifacts-api/snapshots/8.x.json

[8.x] Manually bump 8.x to 8.19.0-SNAPSHOT

---

.ci/bump-golang.yml
.github/dependabot.yml
.github/workflows/bump-elastic-stack-snapshot.yml
.github/workflows/bump-golang.yml

Bump versions for the updatecli and enable dependabot.
Let's try to fix the existing issue with https://github.com/elastic/fleet-server/pull/4353#issuecomment-2613966957 
I created `https://github.com/v1v/fleet-server/pull/9` using my fork and local changes
```bash
$ GIT_USER=v1v GIT_EMAIL=v1v@v1v.com GITHUB_TOKEN=$(gh auth token) updatecli apply --config .ci/bump-golang.yml
```
see https://github.com/elastic/fleet-server/actions/runs/12965426929 and https://github.com/elastic/fleet-server/actions/runs/12965447758
I can see https://github.com/elastic/fleet-server/pull/4323/commits hence it's much better now, or at least, I can see it didn't close it with a force push.

deps(github-actions): bump updatecli version

---

catalog-info.yaml

New minor 9 branches are not running any CI.
No need to build tags, those tags are always coming from a commit that has already ran the CI.

ci: enable 9.* branches

---

.github/dependabot.yml

Dependabot PR's ping `Team:Fleet` unnecessarily. 
Removes the `Team:Fleet` label from dependabot config. 
N/A

Remove Team:Fleet from dependabot.yml

---

catalog-info.yaml

Restore buildkite settings to trigger builds on tags.
This are required to trigger the step:
https://github.com/elastic/fleet-server/blob/6bee16f1ea9ae8aa5fc6a0adff2752a675343fce/.buildkite/pipeline.yml#L207-L215
- Follows #4433

[CI] Update Buildkite configuration for tags in main pipeline

---

internal/pkg/api/handleCheckin_test.go
internal/pkg/api/handleEnroll_test.go
internal/pkg/checkin/bulk_test.go

Add unit tests as a sanity check to make sure that fleet-server is able to handle the new `fips` metadata attribute.
fleet-server uses `json.RawMessage` when interacting with local metadata (in the enroll and checkin endpoints) as it just needs to compare byte values to see if the agent doc needs to be changed. The new tests verify that local metadata changes are propagated as expected.

Add unit test for fips metadata attribute in enroll/checkin

---

Dockerfile.build
Makefile

- Use https://github.com/elastic/golang-crossbuild/pull/527
- Use the specific golang-crossbuild image for `arm64` in arm64
In the CI, we ran https://buildkite.com/elastic/fleet-server-package-mbp/builds/1673

use golang-crossbuild native to ARM64

---

internal/pkg/server/agent_integration_test.go

Just updating retries in agent tests from 120x100ms to 180x100ms. 
120 is on the fence with new default retry strategy

More relaxed retries in agent tests

---

internal/pkg/bulk/setup_test.go
internal/pkg/es/client.go

Removes the `es.WithUsrPwd` to ensure that it is not used outside of tests.
Prevents mis-use in production code.

Remove WithUsrPwd

---

.buildkite/pipeline.yml
.buildkite/scripts/unit_test.sh
Makefile

Validate FIPS compliance by using go 1.24's fips features.
Add a new target that uses [GODEBUG=fips140=only](https://go.dev/doc/security/fips140) to run unit tests.
This target should use the `FIPS=true` flag in order to pass `-tags=requirefips`.
Note that this target assumes golang/go and **NOT** microsoft/go.
In order to use microsoft/go to run these test we would need to install in the environment, and have a FIPS enabled OpenSSL on the system.
`FIPS=true make test-unit-fips`
- ~~I have included fail safe mechanisms to limit the load on fleet-server: rate …

Add go1.24 GODEBUG=fips140=only test

---

.github/dependabot.yml

The dependencies in `/pkg/api/go.mod` and `/testing/go.mod` were not updated automatically, resulting in outdated and potentially vulnerable packages being used. As for the `/go.mod` updates, we were only updating Elastic dependencies. 
We should be updating all dependencies (not only Elastic ones) in all go.mod files across the repository.
Configures Dependabot to update all dependencies in all three `go.mod` files.

chore(deps): configure Dependabot to update all dependencies

---

.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/pipeline.package.mbp.yml
.buildkite/scripts/common.sh
.buildkite/scripts/dra_release.sh
.buildkite/scripts/local_build.sh
.buildkite/scripts/package.sh
.buildkite/scripts/test-release.sh
Dockerfile.fips
Makefile
dev-tools/e2e/Dockerfile
dev-tools/e2e/build.sh
docs/fips.md
testing/e2e/fips_test.go

Provide FIPS dra artifacts.
Add `FIPS="true"` env flag to packageing pipeline.
Packaging pipline uses microsoft/go instead of golang/go to build DRA artifacts for FIPS.
Change package name from `fleet-server-*-fips` to `fleet-server-fips-*`.
- ~~I have added an entry in …

Add DRA FIPS artifacts to package pipeline

---

internal/pkg/config/pbkdf2.go
internal/pkg/config/pbkdf2_test.go

Follow up to https://github.com/elastic/fleet-server/pull/4542 to match the `pbkdf2` validation with the fips requirements and the error message. 
The PR adds unit tests
No design impacting changes
https://github.com/elastic/fleet-server/pull/4542

(fips): match pbkdf2 validation with requirements and error msg

---

.mergify.yml

Removes `8.16` as a targeted branch for the `backport-active-all` and `backport-active-8` labels used by Mergify.

[mergify] Remove 8.16 as an active branch

---

internal/pkg/api/handleAck.go
internal/pkg/api/handleAck_test.go

`upgrade_attempts` were not cleared correctly when agent doesn't have `upgrade_details` (for example in horde or older versions).
Clear `upgrade_attempts` when upgrade is acked (at the same time when `upgrade_started_at` field is cleared).
Test with agent policy with auto upgrade config and a few horde agents enrolled. Verify that after the upgrade completed, `upgrade_attempts` is set to `null`.
The `upgrade_attempts` field is only cleared if there is no `upgrade_details`. Tested with a real agent upgraded to a non-existent version, the agent going to `UPG_FAILED` state.
Relates https://github.com/elastic/fleet-server/pull/4528
Relates https://github.com/elastic/kibana/pull/212744

Clear upgrade_attempts on handleAck

---

changelog/fragments/1743692296-fix-url-parsing-es-output-diagnostics.yaml
internal/pkg/config/output.go
internal/pkg/config/output_test.go

Hosts in the Elasticsearch output are usually set without their scheme, in that case DiagRequests was not correctly parsing the URL, and errors like the following ones appear in the `fleet-server-output-request.txt` file in diagnostics:
```
2025/03/12 13:02:45.560990 No TLS settings
2025/03/12 13:02:45.560994 Proxy disable=false url=<nil>
2025/03/12 13:02:45.561027 Request 0 to somehost:2143 starting
2025/03/12 13:02:45.561049 request 0 error: unsupported protocol scheme "somehost"
```
```
Unable to transform host "127.0.0.1:37603" to url.URL: parse "127.0.0.1:37603": first path segment in URL cannot contain colon
error: 0 requests
```
Instead of parsing the URL and try to add the scheme later, use the `makeURL` helper, that already takes these cases into account.
Check fleet-server …

Fix diagnostic requests when scheme is not included in host

---

changelog/fragments/1744046917-Redact-output-in-bootstrap-config-logs.yaml
internal/pkg/config/config.go
internal/pkg/server/agent.go

Redact output config during bootstrap config handling.
Unpack map into `config.Output` and use existing redaction mechanisms.

Redact output log lines during bootstrap config

---

changelog/fragments/1744831791-Add-version-metadata-to-version-command-output.yaml
cmd/fleet/main.go
internal/pkg/build/build.go
internal/pkg/build/fips.go
internal/pkg/build/nofips.go

We are not able to determine if a fleet-server binary is a FIPS distribution or not.
Add build commit, build time, and FIPS distribution indicator to the output of the version command. Add FIPS distribution indicator to initial log line.
Run: `./fleet-server -v`
Example output:
```
./bin/fleet-server -v
fleet-server version 9.1.0 [5500121e built 2025-04-16 19:28:02 +0000 UTC] (FIPS-distribution: false)
```
- ~~I have made …

Add version metadata to version command

---

changelog/fragments/1745450998-Add-rollback-attribute-to-Upgrade-actions.yaml
internal/pkg/api/openapi.gen.go
model/openapi.yml
pkg/api/types.gen.go

Fleet does not support explicit rollbacks to earlier versions.
Add an attribute to upgrade actions that indicate that the agent will rollback.
- ~~I have added tests that prove my fix is effective or that my feature …

Add rollback attribute to upgrade actions

---

Makefile
docs/fips.md
testing/e2e/fips_test.go

Add the `ms_tls13kdf` build tag to FIPS builds.
microsoft/go TLSv1.3 kdf support (https://github.com/microsoft/go/pull/1662) requires the `ms_tls13kdf` build tag.

Add ms_tls13kdf tag when requirefips is passed

---

.buildkite/pipeline.yml

Reenable benchmarks steps that had to be disabled for the mage migration

Reenable benchmark steps

---

magefile.go

.zip artifacts are incorrectly created so not all tools are able to extract them.
Ensure that the distribution folder is created within the artifact
```bash
SNAPSHOT=true PLATFORMS=windows/amd64 mage build:release
unzip build/distributions/fleet-server-9.1.0-SNAPSHOT-windows-x86_64.zip
```

Ensure directory is made within zip artifacts

---

Dockerfile.fips
magefile.go

Change FIPS build base images to golang-crossbuild.
Change arm base to debian11.
`FIPS=true mage docker:[image|binary]`

Change FIPS build base images to golang-crossbuild

---

changelog/fragments/1750971846-Include-error-on-json-decode-error-responses.yaml
internal/pkg/api/error.go
internal/pkg/api/handleAck_test.go
internal/pkg/api/handleAudit_test.go
internal/pkg/api/handleCheckin_test.go
internal/pkg/api/handleEnroll_test.go

There is no information on why request bodies fail to decode as JSON
Include the base json decode error as part of the response.

Include base error for json decode error responses

---

.ci/bump-golang.yml

We have [automation](https://github.com/elastic/elastic-agent/blob/main/.ci/updatecli/updatecli-bump-golang.yml) to bump Golang versions in this repository.  This PR updates that automation to add the `backport-active-all` label on generated PRs so that, when those PRs are merged into `main`, Mergify automatically creates their backports to all active branches.
To keep the Golang version in sync across all active branches.
(Also to get @pkoutsovasilis [off my back](https://github.com/elastic/fleet-server/pull/5122#issuecomment-3054219562) 😉)

Add `backport-active-all` label to Golang bump PRs

---

.github/workflows/post-dependabot.yml

We run a Github Actions job for dependabot PRs where we update the notice files. However, this job fails for PRs which only touch the `testing` directory. See https://github.com/elastic/fleet-server/pull/5161 for example.
The check currently uses git diff-index, which can give false positives if the file's modification time has changed, but the content hasn't. Our job regenerates both go.sum and the notice files, so their modification times change even if the content doesn't. Use git diff instead, which will silently run git update-index --refresh in this case.
See https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-diffautoRefreshIndex and https://git-scm.com/docs/git-diff-index#_non_cached_mode for more details. Also see https://git-scm.com/docs/racy-git if you're interested in …

Fix changed files check in the post-dependabot GHA job

---

testing/e2e/agent_install_test.go

Agent install test fails on version bump as fleet-server's version is used to lookup the agent download but the agent DRA may not have been produced yet.
Use `ELASTICSEARCH_VERSION` which is tied to the latest released DRA for the version. This version may be smaller than fleet-server's i.e., `9.0.X-1`, but should not be greater so our tests will pass.
`mage test:e2e`

Use ELASTICSEARCH_VERSION instead of fleet-server's version when downloading agent

---

dev-tools/cloud/terraform/main.tf
dev-tools/cloud/terraform/outputs.tf

Cloude2e tests fail on version updates as fleet-server's default version is higher than the latest available cloud version.
Use integration/.env ELASTICSEARCH_VERSION as stack version for cloude2e

Use integration/.env ELASTICSEARCH_VERSION as stack version for cloude2e

---

.buildkite/hooks/pre-command
.buildkite/pipeline.yml
dev-tools/cloud/terraform/main.tf

FIPS cloud tests are not in the correct environment.
Redirect FIPS cloud e2e tests to use FHR-Staging.
Use bk plugins instead of hooks for setting the EC_API key. Add region and deployment template vars to cloude2e terraform.
- Relates https://github.com/elastic/elastic-agent/pull/9198

Redirect FIPS cloud e2e tests to FRH-Staging

---

changelog/fragments/1755810145-Reset-trace-headers-on-bulk-items-when-returning-to-pool.yaml
internal/pkg/bulk/block.go

Bulker items can have a previous item's trace links.
Clear the reference to the trace link in the block's reset method. This method is called before a block is put back in the sync.Pool.
Note that this fix would only apply to functions using the bulker without a transaction tied to their context.

Reset trace headers for bulk items when returning to pool

---

NOTICE-fips.txt
NOTICE.txt
changelog/fragments/1756409821-Restore-connection-limiter.yaml
go.mod
internal/pkg/api/server.go
internal/pkg/limit/listener.go
internal/pkg/limit/listener_test.go

Use of only the throttle middleware can result in OOM incidents under high load.
Restore connection level limiter to prevent OOM incidents. (removed in #4402)
This limiter is used in addition to the request-level throttle so that once
our in-flight requests reaches max_connections a 429 is returned, but if the
total connections the server uses is over max_connections*1.1 the server drops
the connection before the TLS handshake.

Restore connection-level limiter

---

internal/pkg/server/agent.go
internal/pkg/server/agent_test.go
internal/pkg/ver/check.go
testing/e2e/scaffold/scaffold.go

Fix flakey tests seen in https://github.com/elastic/fleet-server/pull/5384 and https://github.com/elastic/fleet-server/pull/5383.
Add logging to help debug agent container test issues.

Fix configFromUnit test, add logging for e2e tests

---

docs/docset.yml
docs/release-notes/index.md
docs/release-notes/toc.yml

Related to https://github.com/elastic/fleet-server/pull/5374
Adds a stub page for the Fleet Server Markdown release notes to prevent failing docs checks on `main` while we wait for https://github.com/elastic/fleet-server/pull/5374 to be reviewed/merged.

[docs] Add stub page for Markdown release notes

---

Dockerfile
magefile.go

PR [#5400](https://github.com/elastic/fleet-server/pull/5400) introduced building serverless images with `golang-crossbuild`.  
This caused failures in the `Publish docker image` step ([example](https://buildkite.com/elastic/fleet-server/builds/10400#01991afe-4fb0-4396-aa98-06474a3fc47b)) on `main` because the `docker:publish` mage target never sets the `SUFFIX` build-arg.
This PR switches serverless images to `golang:${GO_VERSION}-trixie`, which removes the need for a suffix.  
I avoided `golang-crossbuild` because `docker:publish` relies on buildx for multi-platform builds, while `golang-crossbuild` uses image tags per arch. That mismatch could lead to hidden issues.  
I’m still unsure how the FIPS variant works with `docker:publish`, but it doesn’t appear to be actively used. I’ll sync …

fix: switch Dockerfile of serverless image to debian trixie

---

docs/release-notes/known-issues.md

Add a known-issue for the missing `local_metadata.complete` mapping.
This issue is still ongoing (even though the attribute has been added to the template) as we have missed updating `managed_index_mappings_version`, see [the discussion](https://github.com/elastic/elasticsearch/pull/134711#issuecomment-3291957962).

Add a known-issues entry for missing attributes
